# --- curriculum: bubble_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# BUBBLE SORT  (Sorting / simple)
#
# MENTAL MODEL
#   Sweep left to right swapping any out-of-order neighbours. Each full
#   sweep drags the largest remaining value to the end like a bubble rising,
#   so after pass i the last i slots are final. Stop early if a sweep makes
#   no swaps.
#
# INVARIANT
#   After pass i, arr[n-i:] holds the i largest values, sorted.
#
# COMPLEXITY  best O(n) | avg O(n^2) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable yes  in-place yes  adaptive yes
#
# REACH FOR IT WHEN
#   Teaching, or n is tiny and you want the shortest correct code.
#
# AVOID WHEN
#   Always, in production. Insertion sort dominates it at every size.
#
# PITFALLS
#   1. Inner loop bound must be n-i-1; using n-1 reads past the end or
#      wastes comparisons over the already-final tail.
#   2. Without the swapped flag it is O(n^2) even on sorted input, which
#      loses the only property that makes it interesting.
#   3. Comparing arr[j] > arr[j+1] (not >=) is what keeps it stable;
#      flipping to >= silently breaks stability.
#
# SEE ALSO    insertion_sort, cocktail_shaker_sort, odd_even_sort
#
# INTERVIEW
#   - Rarely asked directly — asked as 'why is this slow?'
#   - Counting inversions (bubble's swap count = inversion count)
# --- end curriculum ---

def bubble_sort(arr):
    """
    Sorts the input list 'arr' in-place using Bubble Sort.

    Time Complexity: O(N^2)
    Space Complexity: O(1) (in-place)
    """
    n = len(arr)
    for i in range(n):
        # Track if any swap happens in this pass
        swapped = False
        # Last i elements are already sorted
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                # Swap if out of order
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
                swapped = True
        # If no swaps, list is already sorted
        if not swapped:
            break
    return arr  # Optional: for chaining, not required
