# --- curriculum: insertion_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# INSERTION SORT  (Sorting / simple)
#
# MENTAL MODEL
#   How you sort a dealt hand of cards. Keep a sorted prefix; take the next
#   element and slide it left past everything larger until it lands. The
#   shifting, not swapping, is what makes it fast in practice.
#
# INVARIANT
#   Before iteration i, arr[:i] is sorted (but not yet final).
#
# COMPLEXITY  best O(n) | avg O(n^2) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable yes  in-place yes  adaptive yes
#
# REACH FOR IT WHEN
#   n < ~32, or the data is nearly sorted. This is why every serious hybrid
#   sort (timsort, introsort) falls back to it at small sizes.
#
# AVOID WHEN
#   Large random input — the O(n^2) is real, not theoretical.
#
# PITFALLS
#   1. Shifting with arr[j+1] = arr[j] then placing the key once is O(n)
#      writes per element; swapping instead triples the write traffic.
#   2. The while guard needs j >= 0 checked before arr[j] > key, or Python's
#      negative indexing silently wraps to the end of the list.
#   3. Its O(n) best case only holds if you break out of the inner loop;
#      scanning the whole prefix regardless loses adaptivity.
#
# SEE ALSO    bubble_sort, shell_sort, tim_sort, gnome_sort
#
# INTERVIEW
#   - Insertion Sort List (LC 147)
#   - Sort a k-sorted / nearly-sorted array
# --- end curriculum ---

def insertion_sort(arr):
    """
    Sorts the input list 'arr' in-place using Insertion Sort.

    Time Complexity: O(N^2) worst/average, O(N) best (already sorted)
    Space Complexity: O(1) (in-place)
    """
    n = len(arr)
    for i in range(1, n):
        key = arr[i]
        j = i - 1
        # Move elements greater than key one position ahead
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        # Insert key after shifting
        arr[j + 1] = key
    return arr  # Optional, for chaining
