# --- curriculum: selection_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# SELECTION SORT  (Sorting / simple)
#
# MENTAL MODEL
#   Scan the unsorted suffix for its minimum, swap it into the front of that
#   suffix, repeat. The distinguishing feature is the write count: exactly
#   n-1 swaps, no matter how scrambled the input is.
#
# INVARIANT
#   After pass i, arr[:i+1] holds the i+1 smallest values, sorted and final.
#
# COMPLEXITY  best O(n^2) | avg O(n^2) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable no  in-place yes  adaptive no
#
# REACH FOR IT WHEN
#   Writes are far more expensive than reads — EEPROM, flash, or a medium
#   with limited write endurance.
#
# AVOID WHEN
#   You need stability, or the input may already be sorted (no early exit
#   exists).
#
# PITFALLS
#   1. Swapping the found minimum is what breaks stability; equal values
#      jump over each other. Shifting instead would fix it and turn the
#      algorithm into insertion sort.
#   2. Comparison count is n(n-1)/2 regardless of input — there is no best
#      case to optimise toward.
#   3. Easy to write the inner loop tracking the minimum *value* instead of
#      its *index*, which then cannot be swapped.
#
# SEE ALSO    heap_sort, bubble_sort, cartesian_tree_sort
#
# INTERVIEW
#   - Kth smallest by partial selection
#   - Why heap sort is 'selection sort with a better bag'
# --- end curriculum ---

def selection_sort(arr):
    """
    Sorts the input list 'arr' in-place using Selection Sort.

    Time Complexity: O(N^2)
    Space Complexity: O(1) (in-place)
    """
    n = len(arr)
    for i in range(n):
        # Assume the minimum is at the current index
        min_idx = i
        # Find the actual minimum in the rest of the array
        for j in range(i + 1, n):
            if arr[j] < arr[min_idx]:
                min_idx = j
        # Swap if needed
        arr[i], arr[min_idx] = arr[min_idx], arr[i]
    return arr  # Optional, for chaining
