# --- curriculum: my_array ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# DYNAMIC ARRAY  (Structures / linear)
#
# MENTAL MODEL
#   Contiguous memory with spare capacity at the end. Appending is O(1)
#   until the buffer fills, at which point you allocate a bigger one and
#   copy everything across. Doubling the capacity makes that copy cost
#   amortise to O(1) per append.
#
# INVARIANT
#   0 <= size <= capacity, and elements occupy exactly slots [0, size).
#
# COMPLEXITY  best O(1) index | avg O(1) amortised append | worst O(n) insert/delete at front
# SPACE       O(n)
#
# REACH FOR IT WHEN
#   You index by position, iterate in order, or care about cache locality.
#   The default sequence.
#
# AVOID WHEN
#   Frequent insertion or deletion in the middle or at the front — that is a
#   linked list's job.
#
# PITFALLS
#   1. Growing by a constant (+1, +10) instead of a factor makes n appends
#      cost O(n^2). Doubling is what buys the amortised O(1).
#   2. Amortised O(1) is not worst-case O(1): one unlucky append pays O(n).
#      That distinction matters for real-time systems.
#   3. Deleting from the middle must shift the tail left; forgetting to
#      decrement size leaves a stale duplicate of the last element.
#
# SEE ALSO    singly_linked_list, stack, queue
#
# INTERVIEW
#   - Design a dynamic array
#   - Why is append amortised O(1)?
#   - Remove Element (LC 27)
#
# LONGER NOTE docs/array.md
# --- end curriculum ---

from typing import Any


class MyArray:
    def __init__(self):
        # Initial capacity — how much space we allocate upfront
        self.capacity = 4

        # Logical size — how many elements are currently stored
        self.count = 0

        # How many times the backing buffer has been doubled. Exposed so the
        # amortised-O(1) claim can be checked rather than taken on trust.
        self.resize_count = 0

        # Backing list simulating a fixed-size array
        self.data = [None] * self.capacity


    def append(self,value):
        """
          Adds a value to the end of the array.
          Amortized Time Complexity: O(1)
          Worst-case (resize): O(n)
        """
        # Check if we need to resize the array
        if self.count == self.capacity:
            self._resize()

        # Add the new value and increment the count
        self.data[self.count] = value
        self.count += 1


    def _resize(self):
        # Doubling (rather than growing by a constant) is what makes a sequence
        # of appends amortise to O(1) each. Every resize copies `count` elements,
        # but the capacity you have to fill before paying again doubles too.
        self.resize_count += 1
        self.capacity *= 2
        new_data = [None] * self.capacity

        # Copy over the old data
        for i in range(self.count):
            new_data[i] = self.data[i]

        self.data = new_data


    def get(self, index):
        """
          Retrieves the value at the specified index.
          Time Complexity: O(1)
        """
        if 0 <= index < self.count:
            return self.data[index]
        raise IndexError("Index out of bounds")


    def pop(self):
        """
          Removes the last element from the array and returns it.
          Time Complexity: O(1)
        """
        if self.count == 0:
            raise IndexError("Pop from empty array")

        value = self.data[self.count - 1]
        self.data[self.count - 1] = None
        self.count -= 1
        return value


    def __len__(self):
        """
          A dunder method
          Returns the number of elements in the array.
          Time Complexity: O(1)
        """
        return self.count


    def __getitem__(self, index: int):
      return self.get(index)


    def __iter__(self):
      """
        Yields the stored elements in order.
        Time Complexity: O(n) to exhaust, O(1) per step

        Without this, Python falls back to the legacy __getitem__ iteration
        protocol — which happens to work, but only because get() raises
        IndexError at the boundary. Defining __iter__ makes the intent explicit
        and lets type checkers see that MyArray is iterable.
      """
      for i in range(self.count):
          yield self.data[i]


    def __contains__(self, value) -> bool:
      """
        Supports `value in array`.
        Time Complexity: O(n)
      """
      return self.contains(value)


    def __str__(self):
      """
      Human-readable string representation.
      Example: [10, 20, 30]
      """
      return str(self.data[:self.count])


    def __repr__(self):
      """
        Developer-friendly string representation.
        Example: MyArray([10, 20, 30], size=3, capacity=4)
      """
      return f"MyArray({self.data[:self.count]}, size={self.count}, capacity={self.capacity})"


    def set(self, index: int, value: Any) -> None:
      """
        Sets the value at the given index. i.e replaces the value at that index.
        Time Complexity: O(1)

        Raises:
            IndexError: If index is invalid
      """
      if index < 0 or index >= self.count:
        raise IndexError("Index out of bounds")

      self.data[index] = value


    def insert(self, index: int, value: Any) -> None:
      """
        Inserts a value at the specified index.
        Time Complexity: O(n) in the worst case (if resizing is needed)

        Raises:
            IndexError: If index is invalid
      """
      if index < 0 or index > self.count:
        raise IndexError("Index out of bounds")

      # Resize if necessary
      if self.count == self.capacity:
          self._resize()

      # Shift elements to the right
      for i in range(self.count, index, -1):
          self.data[i] = self.data[i - 1]

      # Insert the new value
      self.data[index] = value
      self.count += 1


    def delete(self, index: int) -> None:
      """
        Deletes the element at the specified index, shifting remaining elements left.
        Time Complexity: O(n) in worst case
      """
      if index < 0 or index >= self.count:
        raise IndexError("Index out of bounds for delete")

      # Shift elements left
      for i in range(index, self.count - 1):
        self.data[i] = self.data[i + 1]

      # Optional: clear the duplicate at the end
      self.data[self.count - 1] = None
      self.count -= 1


    def clear(self):
      """
        Clears the array, resetting it to an empty state.
        Time Complexity: O(n) for clearing the data
      """
      self.data = [None] * self.capacity
      self.count = 0


    def contains(self, value: Any) -> bool:
      """
        Checks if the array contains a specific value.
        Time Complexity: O(n) in worst case
      """
      for i in range(self.count):
          if self.data[i] == value:
              return True
      return False


    def index_of(self, value: Any) -> int:
      """
        Returns the index of the first occurrence of a value.
        Time Complexity: O(n) in worst case
      """
      for i in range(self.count):
          if self.data[i] == value:
              return i
      return -1



