# --- curriculum: circular_queue ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# CIRCULAR QUEUE (RING BUFFER)  (Structures / linear)
#
# MENTAL MODEL
#   A fixed array where the head and tail indices wrap around with modulo.
#   Nothing is ever shifted and nothing is ever reallocated, so both ends
#   are genuinely O(1) in constant memory.
#
# INVARIANT
#   tail == (head + size) % capacity, and the live elements are the `size`
#   slots starting at head.
#
# COMPLEXITY  best O(1) enqueue | avg O(1) dequeue | worst O(1) peek
# SPACE       O(capacity) fixed
#
# REACH FOR IT WHEN
#   Bounded buffers with fixed memory: audio/video streaming, device
#   drivers, sliding windows, logging.
#
# AVOID WHEN
#   The maximum size is genuinely unknown — a full ring must either reject
#   or overwrite.
#
# PITFALLS
#   1. head == tail is ambiguous: it means both empty and full. Resolve it
#      by tracking size explicitly or by leaving one slot permanently
#      unused. Picking neither is the classic bug.
#   2. Every index advance needs the % capacity; one missing modulo breaks
#      only after the first wrap, so small tests pass.
#   3. Overwrite-when-full versus reject-when-full is a product decision,
#      not a detail — it must be stated in the API.
#
# SEE ALSO    queue, deque, my_array
#
# INTERVIEW
#   - Design Circular Queue (LC 622)
#   - Design Circular Deque (LC 641)
#   - Design Hit Counter (LC 362)
#   - Moving Average from Data Stream (LC 346)
#
# LONGER NOTE docs/circular_queue.md
# --- end curriculum ---

class CircularQueue:
    def __init__(self, capacity: int):
        """
        Initializes a circular queue with fixed capacity.

        Time Complexity: O(1)
        Space Complexity: O(n), where n = capacity

        Parameters:
            capacity (int): The maximum number of elements the queue can hold
        """
        self.capacity = capacity
        self.data = [None] * capacity
        self.front = 0
        self.rear = 0
        self.size = 0


    def enqueue(self, value):
      """
        Adds a value to the rear of the queue.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Raises:
            OverflowError: If the queue is full
      """
      if self.size == self.capacity:
          raise OverflowError("Circular queue is full")

      self.data[self.rear] = value
      self.rear = (self.rear + 1) % self.capacity
      self.size += 1


    def dequeue(self):
      """
        Removes and returns the front element of the queue.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Raises:
            IndexError: If the queue is empty
      """
      if self.size == 0:
          raise IndexError("Dequeue from empty queue")

      value = self.data[self.front]
      self.data[self.front] = None  # Optional: clear slot
      self.front = (self.front + 1) % self.capacity
      self.size -= 1
      return value


    def __len__(self) -> int:
      """
        Returns the number of elements currently in the queue.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            int: current size of the queue
      """
      return self.size


    def peek(self):
      """
        Returns the front element of the queue without removing it.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Raises:
            IndexError: If the queue is empty
      """
      if self.size == 0:
          raise IndexError("Peek from empty queue")

      return self.data[self.front]


    def is_empty(self) -> bool:
      """
        Returns True if the queue is empty, else False.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            bool: True if empty, False otherwise
      """
      return self.size == 0


    def is_full(self) -> bool:
      """
        Returns True if the queue is full, else False.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            bool: True if full, False otherwise
      """
      return self.size == self.capacity


    def __str__(self) -> str:
      """
        Returns a user-friendly string showing queue contents from front to rear.

        Time Complexity: O(n)
        Space Complexity: O(n)

        Returns:
            str: Formatted queue string like: Front → [10, 20, 30] ← Rear
      """
      if self.size == 0:
          return "Front → [] ← Rear"

      result = []
      index = self.front
      for _ in range(self.size):
          result.append(self.data[index])
          index = (index + 1) % self.capacity

      return f"Front → {result} ← Rear"

