# --- curriculum: queue ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# QUEUE (FIFO)  (Structures / linear)
#
# MENTAL MODEL
#   A line at a counter. First in, first out. Where a stack explores
#   depth-first, a queue explores breadth-first — which is exactly why BFS
#   finds shortest paths in unweighted graphs and DFS does not.
#
# INVARIANT
#   Elements leave in the order they arrived; enqueue touches only the tail,
#   dequeue only the head.
#
# COMPLEXITY  best O(1) enqueue | avg O(1) dequeue (with proper backing) | worst O(1) peek
# SPACE       O(n)
#
# REACH FOR IT WHEN
#   BFS, level-order traversal, task scheduling, rate limiting,
#   producer/consumer buffers.
#
# AVOID WHEN
#   You need the most recent item (stack) or access at both ends (deque).
#
# PITFALLS
#   1. A naive list-backed queue using pop(0) is O(n) per dequeue, making
#      BFS O(n^2). Use a head index, a linked list, or a ring buffer.
#   2. Using a plain list and never reclaiming the consumed prefix leaks
#      memory for long-running queues.
#   3. BFS must mark a node visited when it is ENQUEUED, not when dequeued,
#      or nodes get added multiple times.
#
# SEE ALSO    circular_queue, deque, stack, traversals
#
# INTERVIEW
#   - Implement Queue using Stacks (LC 232)
#   - Binary Tree Level Order Traversal (LC 102)
#   - Rotting Oranges (LC 994) — multi-source BFS
#   - Number of Islands (LC 200)
#
# LONGER NOTE docs/queue.md
# --- end curriculum ---

class Queue:
    def __init__(self):
        """
        Initializes an empty queue using a list.

        Time Complexity: O(1)
        Space Complexity: O(1)
        """
        self.data = []

    def enqueue(self, value):
        """
        Adds a value to the rear of the queue.

        Time Complexity: O(1) amortized
        Space Complexity: O(1)

        Parameters:
            value (any): The value to be added to the queue.
        """
        self.data.append(value)


    def dequeue(self):
      """
        Removes and returns the front element from the queue.

        Time Complexity: O(n) due to list shifting
        Space Complexity: O(1)

        Returns:
            The value at the front of the queue

        Raises:
            IndexError: If the queue is empty
      """
      if not self.data:
          raise IndexError("Dequeue from empty queue")

      return self.data.pop(0)


    def peek(self):
      """
        Returns the front element of the queue without removing it.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            The value at the front of the queue

        Raises:
            IndexError: If the queue is empty
      """
      if not self.data:
          raise IndexError("Peek from empty queue")

      return self.data[0]


    def is_empty(self) -> bool:
      """
        Checks whether the queue is empty.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            bool: True if the queue is empty, False otherwise
      """
      return len(self.data) == 0


    def __len__(self) -> int:
      """
        Returns the number of elements currently in the queue.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            int: The current size of the queue
      """
      return len(self.data)


    def __str__(self) -> str:
      """
        Returns a user-friendly string representation of the queue.

        Time Complexity: O(n)
        Space Complexity: O(n)

        Example Output:
            Front → [1, 2, 3] ← Rear
      """
      return f"Front → {self.data} ← Rear"




