# --- curriculum: stack ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# STACK (LIFO)  (Structures / linear)
#
# MENTAL MODEL
#   A pile where you can only touch the top. Last in, first out. The reason
#   it appears everywhere is that it mirrors nesting — function calls,
#   brackets, undo history, and any 'most recent unmatched thing' question.
#
# INVARIANT
#   The only accessible element is the one most recently pushed and not yet
#   popped.
#
# COMPLEXITY  best O(1) push | avg O(1) pop | worst O(1) peek
# SPACE       O(n)
#
# REACH FOR IT WHEN
#   Anything with nesting or backtracking: expression parsing, DFS, undo,
#   monotonic-stack problems.
#
# AVOID WHEN
#   You need access to the oldest element — that is a queue.
#
# PITFALLS
#   1. Pop and peek on an empty stack must raise, not return None: None is a
#      legitimate stored value and silently conflating them hides bugs.
#   2. Array-backed pop from the END is O(1); popping from index 0 is O(n)
#      and turns the structure into a slow queue.
#   3. Recursion IS an implicit stack. Converting recursion to iteration
#      means making that stack explicit, which is the usual follow-up.
#
# SEE ALSO    queue, my_array, traversals, singly_linked_list
#
# INTERVIEW
#   - Valid Parentheses (LC 20)
#   - Min Stack (LC 155)
#   - Daily Temperatures (LC 739) — monotonic stack
#   - Largest Rectangle in Histogram (LC 84)
#   - Evaluate Reverse Polish Notation (LC 150)
#
# LONGER NOTE docs/stack.md
# --- end curriculum ---

class Stack:
    def __init__(self):
        """
        Initializes an empty stack using a dynamic array (Python list).

        Time Complexity: O(1)
        Space Complexity: O(1)
        """
        self.data = []

    def push(self, value):
        """
        Pushes a new value onto the top of the stack.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Parameters:
            value (any): The value to be added to the stack.
        """
        self.data.append(value)

    def pop(self):
      """
        Removes and returns the top element from the stack.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            The last pushed element (top of the stack)

        Raises:
            IndexError: If the stack is empty
      """
      if not self.data:
          raise IndexError("Pop from empty stack")

      return self.data.pop()

    def peek(self):
      """
        Returns the top element of the stack without removing it.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            The last pushed element (top of the stack)

        Raises:
            IndexError: If the stack is empty
      """
      if not self.data:
          raise IndexError("Peek from empty stack")

      return self.data[-1]


    def is_empty(self) -> bool:
      """
        Checks whether the stack is empty.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            bool: True if stack is empty, False otherwise
      """
      return len(self.data) == 0

    def __len__(self) -> int:
      """
        Returns the number of elements in the stack.

        Time Complexity: O(1)
        Space Complexity: O(1)

        Returns:
            int: The number of elements in the stack
      """
      return len(self.data)

    def __str__(self) -> str:
      """
        Returns a user-friendly string representation of the stack.

        Example Output:
            Bottom → [1, 2, 3] ← Top

        Time Complexity: O(n)
        Space Complexity: O(n)
      """
      return f"Bottom → {self.data} ← Top"



