# --- curriculum: binary_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# BINARY SEARCH (ITERATIVE)  (Searching / binary)
#
# MENTAL MODEL
#   Maintain a window that must contain the answer if it exists. Compare the
#   middle; discard the half that cannot contain the target. Every step
#   halves the window, so log2(n) steps suffice. The hard part is never the
#   idea — it is the boundary arithmetic.
#
# INVARIANT
#   If the target is present, its index lies in [left, right]. Every
#   iteration must strictly shrink that window.
#
# COMPLEXITY  best O(1) | avg O(log n) | worst O(log n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Sorted, randomly-accessible data. Also any monotone predicate — see
#   ubiquitous_binary_search.
#
# AVOID WHEN
#   Unsorted data, linked lists (no O(1) indexing), or a single lookup on
#   unsorted input.
#
# PITFALLS
#   1. left + (right - left) // 2 rather than (left + right) // 2 avoids
#      integer overflow. Irrelevant in Python, but it is the canonical
#      answer and the reason is worth knowing.
#   2. while left <= right with right = mid - 1 is the closed-interval form.
#      Mixing it with the half-open form (right = mid, while left < right)
#      gives an off-by-one or an infinite loop.
#   3. It returns SOME matching index, not the first. Leftmost/rightmost
#      bounds need the variant that keeps searching after a hit.
#   4. Requires the array to actually be sorted. It fails silently, not
#      loudly, on unsorted input.
#
# SEE ALSO    recursive_binary_search, ubiquitous_binary_search, exponential_search, rotated_binary_search, interpolation_search
#
# INTERVIEW
#   - Binary Search (LC 704)
#   - First Bad Version (LC 278)
#   - Search Insert Position (LC 35)
#   - Find First and Last Position (LC 34)
# --- end curriculum ---

from typing import Any


def binary_search(arr: list[Any], target: Any) -> int:
    """
    Basic Iterative Binary Search on a sorted (ascending) array.

    Args:
        arr (List[Any]): Sorted array to search.
        target (Any): Value to search for.

    Returns:
        int: Index of target if found, else -1.

    Time Complexity: O(log n)
    Space Complexity: O(1)
    """
    left, right = 0, len(arr) - 1

    while left <= right:
        mid = left + (right - left) // 2  # Avoids overflow in other languages
        if arr[mid] == target:
            return mid
        if arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1
