# --- curriculum: exponential_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# EXPONENTIAL SEARCH  (Searching / binary)
#
# MENTAL MODEL
#   Find a bound before you bisect. Double the index (1, 2, 4, 8, ...) until
#   you overshoot the target, then binary search the last doubled range.
#   Total O(log i) where i is the answer's index — independent of the
#   array's total length.
#
# INVARIANT
#   When the doubling stops at bound b, the target (if present) lies in
#   [b//2, min(b, n-1)].
#
# COMPLEXITY  best O(1) | avg O(log i) | worst O(log n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Unbounded or unknown-length sorted input (a sorted stream, an API that
#   404s past the end), or when the target is expected near the front.
#
# AVOID WHEN
#   Plain bounded arrays where the target is uniformly distributed — plain
#   binary search is simpler.
#
# PITFALLS
#   1. Check arr[0] first. The doubling loop starts at index 1 and would
#      otherwise never test index 0.
#   2. The upper bound must be clamped to n-1 before the binary search, or
#      it indexes past the end.
#   3. It is O(log i), not O(log n). That is the whole selling point and the
#      thing interviewers are listening for.
#
# SEE ALSO    binary_search, jump_search, fibonacci_search
#
# INTERVIEW
#   - Search in a Sorted Array of Unknown Size (LC 702)
#   - Find the length of an unbounded sorted stream
# --- end curriculum ---

from typing import Any


def exponential_search(arr: list[Any], target: Any) -> int:
    """
    Exponential Search for sorted arrays.
    Quickly finds the window containing the target, then uses binary search.

    Args:
        arr (List[Any]): Sorted array (ascending).
        target (Any): Value to search for.

    Returns:
        int: Index of target if found, else -1.

    Time Complexity: O(log position of target)
    Space Complexity: O(1)
    """
    n = len(arr)
    if n == 0:
        return -1
    if arr[0] == target:
        return 0

    # Find range by repeated doubling
    i = 1
    while i < n and arr[i] <= target:
        i *= 2

    # Binary search in the found range: [i//2, min(i, n-1)]
    left = i // 2
    right = min(i, n - 1)
    while left <= right:
        mid = left + (right - left) // 2
        if arr[mid] == target:
            return mid
        if arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1

    return -1
