# --- curriculum: fibonacci_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# FIBONACCI SEARCH  (Searching / binary)
#
# MENTAL MODEL
#   Binary search that splits by Fibonacci numbers instead of halving. The
#   split points only ever move forward by addition and subtraction — no
#   division — and each probe is nearer the previous one, which suited tape
#   and drum storage.
#
# INVARIANT
#   The remaining window length is always a Fibonacci number, and probe
#   offsets are computed by subtraction alone.
#
# COMPLEXITY  best O(1) | avg O(log n) | worst O(log n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Hardware without division, or non-uniform access cost where probe
#   locality matters (tape, spinning disk).
#
# AVOID WHEN
#   Ordinary RAM. Binary search is simpler and identical asymptotically.
#
# PITFALLS
#   1. The comparison count is marginally WORSE than binary search — the win
#      is arithmetic simplicity and probe locality, not fewer probes.
#   2. The Fibonacci numbers must be generated up to >= n before the search
#      starts; generating them lazily inside the loop loses the point.
#   3. The probe index must be clamped with min(offset + fib, n-1).
#
# SEE ALSO    binary_search, exponential_search, ternary_search
#
# INTERVIEW
#   - Trivia; good answer to 'search without using division'
# --- end curriculum ---

from typing import Any


def fibonacci_search(arr: list[Any], target: Any) -> int:
    """
    Fibonacci Search for sorted arrays (ascending order).

    Args:
        arr (List[Any]): Sorted array (ascending).
        target (Any): Value to search for.

    Returns:
        int: Index of target if found, else -1.

    Time Complexity: O(log n)
    Space Complexity: O(1)
    """
    n = len(arr)
    # Initialize Fibonacci numbers
    fibM2, fibM1 = 0, 1
    fibM = fibM1 + fibM2

    # Find the smallest Fibonacci number >= n
    while fibM < n:
        fibM2, fibM1 = fibM1, fibM
        fibM = fibM1 + fibM2

    # Marks the eliminated range from the front
    offset = -1

    while fibM > 1:
        # Check if fibM2 is a valid location
        i = min(offset + fibM2, n - 1)
        if arr[i] < target:
            fibM = fibM1
            fibM1 = fibM2
            fibM2 = fibM - fibM1
            offset = i
        elif arr[i] > target:
            fibM = fibM2
            fibM1 = fibM1 - fibM2
            fibM2 = fibM - fibM1
        else:
            return i

    # Compare the last element
    if fibM1 and offset + 1 < n and arr[offset + 1] == target:
        return offset + 1

    return -1
