# --- curriculum: interpolation_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# INTERPOLATION SEARCH  (Searching / binary)
#
# MENTAL MODEL
#   How a human uses a phone book: looking for 'Aaron', you open near the
#   front, not the middle. Estimate the position by linear interpolation
#   between the window's endpoint values. On uniformly distributed data this
#   gives O(log log n).
#
# INVARIANT
#   Same window invariant as binary search; only the choice of probe
#   position differs.
#
# COMPLEXITY  best O(1) | avg O(log log n) if uniform | worst O(n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Sorted AND approximately uniformly distributed numeric keys —
#   timestamps, sequential IDs, sensor readings.
#
# AVOID WHEN
#   Skewed or clustered distributions. Exponentially-spaced values degrade
#   it to O(n), worse than binary search.
#
# PITFALLS
#   1. Division by zero when arr[high] == arr[low] — must be guarded before
#      computing the probe.
#   2. The probe position must be bounds-checked: interpolation can point
#      outside [low, high] when the target is out of range.
#   3. Its advantage is entirely distribution-dependent. On adversarial
#      input it is strictly worse than binary search, which is the trade-off
#      to name out loud.
#
# SEE ALSO    binary_search, bucket_sort, jump_search
#
# INTERVIEW
#   - When does binary search lose to something else?
#   - Searching uniformly distributed keys
# --- end curriculum ---

from typing import Any


def interpolation_search(arr: list[Any], target: Any) -> int:
    """
    Interpolation Search for uniformly distributed, sorted arrays.

    Args:
        arr (List[Any]): Sorted array (preferably uniformly distributed).
        target (Any): The value to search for.

    Returns:
        int: Index of target if found, else -1.

    Time Complexity:
        Best/Average: O(log log n) for uniform arrays
        Worst: O(n) for non-uniform or clustered data
    Space Complexity: O(1)
    """
    left, right = 0, len(arr) - 1

    while left <= right and arr[left] <= target <= arr[right]:
        # Handle single-value segment to avoid division by zero
        if arr[left] == arr[right]:
            if arr[left] == target:
                return left
            return -1

        # Estimate the probable position of the target
        pos = left + ((target - arr[left]) * (right - left)) // (arr[right] - arr[left])

        # Guard against out-of-bounds due to integer division
        if pos < left or pos > right:
            return -1

        if arr[pos] == target:
            return pos
        if arr[pos] < target:
            left = pos + 1
        else:
            right = pos - 1

    return -1
