# --- curriculum: recursive_binary_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# BINARY SEARCH (RECURSIVE)  (Searching / binary)
#
# MENTAL MODEL
#   The same halving, expressed as a recurrence: T(n) = T(n/2) + O(1). Reads
#   closer to the proof than the loop does, at the cost of O(log n) stack
#   frames.
#
# INVARIANT
#   Each call is handed a window that contains the target if it exists
#   anywhere.
#
# COMPLEXITY  best O(1) | avg O(log n) | worst O(log n)
# SPACE       O(log n) stack
#
# REACH FOR IT WHEN
#   When the recurrence makes the argument clearer — teaching, or proving
#   correctness.
#
# AVOID WHEN
#   Hot paths. log n frames is cheap but not free, and the loop form is no
#   harder to read.
#
# PITFALLS
#   1. A mutable default like right=None must be resolved on the first call
#      only; re-deriving len(arr) every call is harmless here but the habit
#      breaks other recursions.
#   2. The base case is left > right, returning -1. Using left == right
#      misses single-element windows.
#   3. Must return the recursive call's value. Calling without returning
#      yields None, which is falsy like -1 and so passes sloppy tests.
#
# SEE ALSO    binary_search, recursive_linear_search
#
# INTERVIEW
#   - Same problems as binary search; state the O(log n) space cost
# --- end curriculum ---

from typing import Any


def recursive_binary_search(arr: list[Any], target: Any, left: int = 0, right: int = None) -> int:
    """
    Recursive Binary Search on a sorted (ascending) array.

    Args:
        arr (List[Any]): Sorted array to search.
        target (Any): Value to search for.
        left (int): Left index of current search window.
        right (int): Right index of current search window.

    Returns:
        int: Index of target if found, else -1.

    Time Complexity: O(log n)
    Space Complexity: O(log n) due to recursion stack.
    """
    if right is None:
        right = len(arr) - 1
    if left > right:
        return -1

    mid = left + (right - left) // 2

    if arr[mid] == target:
        return mid
    if arr[mid] < target:
        return recursive_binary_search(arr, target, mid + 1, right)
    return recursive_binary_search(arr, target, left, mid - 1)
