# --- curriculum: rotated_binary_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# ROTATED ARRAY BINARY SEARCH  (Searching / binary)
#
# MENTAL MODEL
#   A sorted array rotated at an unknown pivot. Crucially, at least one half
#   of any window is still properly sorted. Identify which half that is,
#   test whether the target falls inside its range, and discard one half as
#   usual.
#
# INVARIANT
#   For any window, arr[low] <= arr[mid] implies the left half is sorted;
#   otherwise the right half is. The target's membership in the sorted half
#   is then a simple range test.
#
# COMPLEXITY  best O(1) | avg O(log n) | worst O(log n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Circular buffers, sorted data with an unknown offset, any 'sorted then
#   rotated' problem.
#
# AVOID WHEN
#   Duplicates are present — they break the sorted-half test and force O(n)
#   worst case.
#
# PITFALLS
#   1. Duplicates are the killer: with [1,1,1,0,1] you cannot tell which
#      half is sorted, and the worst case becomes O(n). That is LC 81 versus
#      LC 33.
#   2. The range test on the sorted half must be inclusive at both ends, or
#      boundary targets are missed.
#   3. Using arr[low] <= arr[mid] (not <) matters for two-element windows.
#
# SEE ALSO    binary_search, ubiquitous_binary_search
#
# INTERVIEW
#   - Search in Rotated Sorted Array (LC 33)
#   - Search in Rotated Sorted Array II (LC 81) — with duplicates
#   - Find Minimum in Rotated Sorted Array (LC 153)
# --- end curriculum ---

from typing import Any


def rotated_binary_search(arr: list[Any], target: Any) -> int:
    """
    Searches for a target in a rotated sorted array using binary search logic.

    Args:
        arr (List[Any]): Rotated sorted array (ascending, no duplicates).
        target (Any): Value to find.

    Returns:
        int: Index of target if found, else -1.

    Time Complexity: O(log n)
    Space Complexity: O(1)
    """
    left, right = 0, len(arr) - 1

    while left <= right:
        mid = left + (right - left) // 2

        if arr[mid] == target:
            return mid

        # Check which half is sorted
        if arr[left] <= arr[mid]:  # Left half is sorted
            if arr[left] <= target < arr[mid]:
                right = mid - 1
            else:
                left = mid + 1
        else:  # Right half is sorted
            if arr[mid] < target <= arr[right]:
                left = mid + 1
            else:
                right = mid - 1

    return -1
