# --- curriculum: directed_weighted_graph ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# DIRECTED WEIGHTED GRAPH  (Structures / graphs)
#
# MENTAL MODEL
#   Direction plus cost. This is the most general of the four graph shapes
#   and where the heavyweight algorithms live: Bellman-Ford for negative
#   edges, Floyd-Warshall for all-pairs, DAG relaxation in topological
#   order, and max-flow.
#
# INVARIANT
#   weight(u, v) is independent of weight(v, u). Relaxation: dist[v] <=
#   dist[u] + weight(u, v) holds at termination.
#
# COMPLEXITY  best O(1) add edge | avg Bellman-Ford O(VE) | worst Floyd-Warshall O(V^3)
# SPACE       O(V + E)
#
# REACH FOR IT WHEN
#   Currency arbitrage, one-way road networks with tolls, flow networks,
#   PERT/critical-path scheduling.
#
# AVOID WHEN
#   Edges are symmetric — the undirected form halves the storage and the
#   bookkeeping.
#
# PITFALLS
#   1. A negative CYCLE means no shortest path exists (you can loop
#      forever). Bellman-Ford's extra Vth pass is what detects it — skipping
#      that pass returns nonsense confidently.
#   2. On a DAG, relaxing edges in topological order gives shortest paths in
#      O(V+E), beating Dijkstra and tolerating negative weights.
#   3. Floyd-Warshall's loop order must be k (intermediate) OUTERMOST. Any
#      other nesting computes something that is not all-pairs shortest
#      paths.
#   4. Max-flow needs the RESIDUAL graph including backward edges;
#      forgetting them makes Ford-Fulkerson stop at a non-maximal flow.
#
# SEE ALSO    undirected_weighted_graph, directed_graph, min_heap, astar
#
# INTERVIEW
#   - Cheapest Flights Within K Stops (LC 787) — Bellman-Ford
#   - Network Delay Time (LC 743)
#   - Find the City With the Smallest Number of Neighbors (LC 1334) — Floyd-Warshall
#   - Maximum Flow / bipartite matching
# --- end curriculum ---

from Linear.arrays import MyArray as Array
from Linear.singly_linked_list import SinglyLinkedList as LinkedList


class DirectedWeightedGraph:
    """
    Directed Weighted Graph implementation using adjacency lists.
    Each vertex maintains a linked list of (neighbor, weight) pairs.
    """

    def __init__(self, num_vertices: int):
        """
        Initialize a directed weighted graph with the specified number of vertices.

        Args:
            num_vertices (int): Number of vertices (0-based: 0 to num_vertices-1).
        """
        self.n = num_vertices
        self.adj = Array()

        # Each vertex gets its own adjacency list
        for _ in range(num_vertices):
            self.adj.append(LinkedList())

    def _validate_vertex(self, u: int):
        """Raise ValueError if the vertex is out of bounds."""
        if u < 0 or u >= self.n:
            raise ValueError(f"Vertex {u} is out of bounds. Valid range: 0 to {self.n - 1}")

    def add_edge(self, u: int, v: int, weight: float):
        """
        Add a directed edge u -> v with the given weight.

        Time Complexity: O(deg(u))
        """
        self._validate_vertex(u)
        self._validate_vertex(v)

        # Check if edge already exists
        for i in range(len(self.adj[u])):
            neighbor, _ = self.adj[u].get(i)
            if neighbor == v:
                return  # Edge already exists

        self.adj[u].append((v, weight))

    def remove_edge(self, u: int, v: int):
        """
        Remove the directed edge u -> v if it exists.

        Time Complexity: O(deg(u))
        """
        self._validate_vertex(u)
        self._validate_vertex(v)

        for i in range(len(self.adj[u])):
            neighbor, _ = self.adj[u].get(i)
            if neighbor == v:
                self.adj[u].delete(i)
                return

    def has_edge(self, u: int, v: int) -> bool:
        """
        Check if there is a directed edge u -> v.

        Time Complexity: O(deg(u))
        """
        self._validate_vertex(u)
        for i in range(len(self.adj[u])):
            neighbor, _ = self.adj[u].get(i)
            if neighbor == v:
                return True
        return False

    def neighbors(self, u: int):
        """
        Return a list of (neighbor, weight) pairs for vertex u.

        Time Complexity: O(deg(u))
        """
        self._validate_vertex(u)
        result = []
        for i in range(len(self.adj[u])):
            result.append(self.adj[u].get(i))
        return result

    def edges(self):
        """
        Return a list of all directed edges (u, v, weight).

        Time Complexity: O(V + E)
        """
        result = []
        for u in range(self.n):
            for i in range(len(self.adj[u])):
                v, w = self.adj[u].get(i)
                result.append((u, v, w))
        return result

    def vertex_count(self) -> int:
        """Return the total number of vertices."""
        return self.n

    def edge_count(self) -> int:
        """Return the total number of directed edges."""
        count = 0
        for u in range(self.n):
            count += len(self.adj[u])
        return count

    def __len__(self):
        return self.n

    def __str__(self):
        """
        String representation of the graph.
        Each vertex lists its outgoing edges with weights.
        """
        lines = []
        for u in range(self.n):
            neighbors = ", ".join(f"{v}(w={w})" for v, w in self.neighbors(u))
            lines.append(f"{u}: {neighbors}")
        return "\n".join(lines)

    def __repr__(self):
        return f"DirectedWeightedGraph(num_vertices={self.n})"
