# --- curriculum: linear_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# LINEAR SEARCH  (Searching / linear)
#
# MENTAL MODEL
#   Look at every element until you find the target. The only search that
#   requires nothing of the data — no ordering, no indexing, no random
#   access. That is its entire value.
#
# INVARIANT
#   After checking index i, the target is known not to be in arr[:i+1].
#
# COMPLEXITY  best O(1) | avg O(n) | worst O(n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Unsorted data, linked lists, streams, or n small enough that sorting
#   first costs more than scanning.
#
# AVOID WHEN
#   The data is sorted and randomly accessible — binary search is free at
#   that point.
#
# PITFALLS
#   1. Returning a boolean instead of an index throws away information the
#      caller usually needs.
#   2. linear_search_all returns every match; the single-result version
#      returns the FIRST. Confusing the two is a classic off-by-many bug.
#   3. Sorting in order to binary search costs O(n log n) — never worth it
#      for a single lookup.
#
# SEE ALSO    sentinel_search, bidirectional_linear_search, binary_search
#
# INTERVIEW
#   - Baseline for 'can you do better?' follow-ups
#   - Two Sum (LC 1) brute force
# --- end curriculum ---

from typing import Any


def linear_search(arr: list[Any], target: Any) -> int:
    """
    Perform a basic linear search for the target in arr.

    Args:
        arr (List[Any]): The list to search.
        target (Any): The value to find.

    Returns:
        int: Index of target if found; else -1.

    Time Complexity: O(n) where n = len(arr)
    Space Complexity: O(1)
    """
    for i in range(len(arr)):
        if arr[i] == target:
            return i  # Return index at first occurrence
    return -1  # Not found

# Alternate: Return all indices where target appears
def linear_search_all(arr: list[Any], target: Any) -> list[int]:
    """
    Return a list of all indices where target appears in arr.

    Time Complexity: O(n)
    Space Complexity: O(k), k = count of target in arr
    """
    return [i for i, v in enumerate(arr) if v == target]

