# --- curriculum: bidirectional_linear_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# BIDIRECTIONAL LINEAR SEARCH  (Searching / linear)
#
# MENTAL MODEL
#   Scan from both ends toward the middle. Halves the expected number of
#   iterations but not the number of comparisons — each iteration now does
#   two. Still O(n).
#
# INVARIANT
#   After iteration k, the target is known not to be in arr[:k+1] or
#   arr[n-k-1:].
#
# COMPLEXITY  best O(1) | avg O(n/2) iterations, O(n) comparisons | worst O(n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   The target is likely near either end, or you want the wall-clock win
#   from better cache prefetching in two directions.
#
# AVOID WHEN
#   You need the first match in index order — it may find the later one
#   first.
#
# PITFALLS
#   1. It does NOT halve the work: two comparisons per iteration over n/2
#      iterations is the same n comparisons. The asymptotic class is
#      unchanged.
#   2. With duplicates it can return the rightmost match, breaking any
#      caller expecting leftmost-first semantics.
#   3. The loop must stop when left > right, not left == right, or the
#      middle element is checked twice or skipped on odd lengths.
#
# SEE ALSO    linear_search, sentinel_search
#
# INTERVIEW
#   - Honest answer to 'how would you speed up linear search?' — you cannot, asymptotically
# --- end curriculum ---

from typing import Any


def bidirectional_linear_search(arr: list[Any], target: Any) -> int:
    """
    Bidirectional Linear Search:
    Searches for the target from both ends of the array simultaneously.

    Args:
        arr (List[Any]): The array to search.
        target (Any): The value to find.

    Returns:
        int: Index of the first occurrence found (could be left or right side).
             Returns -1 if not found.

    Time Complexity: O(n)
    Space Complexity: O(1)
    """
    start = 0
    end = len(arr) - 1

    while start <= end:
        if arr[start] == target:
            return start
        if arr[end] == target:
            return end
        start += 1
        end -= 1
    return -1
