# --- curriculum: recursive_linear_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# RECURSIVE LINEAR SEARCH  (Searching / linear)
#
# MENTAL MODEL
#   Linear search written as recursion: either index i holds the target, or
#   the answer is in the rest of the array. Pedagogically useful,
#   practically worse — Python has no tail-call elimination.
#
# INVARIANT
#   The call at index i has already ruled out arr[:i].
#
# COMPLEXITY  best O(1) | avg O(n) | worst O(n)
# SPACE       O(n) stack
#
# REACH FOR IT WHEN
#   Demonstrating how an iterative loop maps to a recurrence.
#
# AVOID WHEN
#   Any real array. O(n) stack frames means RecursionError around n=1000 in
#   CPython, where the loop version happily does millions.
#
# PITFALLS
#   1. The base case must be idx >= len(arr), not idx == len(arr) — a caller
#      passing a larger start index otherwise recurses forever.
#   2. Space goes from O(1) to O(n). That is the real cost of the rewrite
#      and the thing to say out loud in an interview.
#
# SEE ALSO    linear_search, recursive_binary_search
#
# INTERVIEW
#   - Convert recursion to iteration and state the space change
# --- end curriculum ---

from typing import Any


def recursive_linear_search(arr: list[Any], target: Any, idx: int = 0) -> int:
    """
    Recursive Linear Search.

    Args:
        arr (List[Any]): The array to search.
        target (Any): The value to find.
        idx (int): Current index (default 0).

    Returns:
        int: Index of target if found, else -1.

    Time Complexity: O(n)
    Space Complexity: O(n) due to recursion stack.
    """
    if idx >= len(arr):    # Base case: reached end
        return -1
    if arr[idx] == target: # Base case: found
        return idx
    return recursive_linear_search(arr, target, idx + 1)  # Recursive call
