# --- curriculum: sentinel_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# SENTINEL LINEAR SEARCH  (Searching / linear)
#
# MENTAL MODEL
#   A linear scan has two checks per step: 'found it?' and 'ran off the
#   end?'. Plant the target in the last slot as a sentinel and the bounds
#   check becomes unnecessary — the loop is guaranteed to stop. One
#   comparison per iteration instead of two.
#
# INVARIANT
#   The target is always present in the array during the scan, so the loop
#   always terminates without a bounds test.
#
# COMPLEXITY  best O(1) | avg O(n) | worst O(n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Tight inner loops in a low-level language where halving per-iteration
#   comparisons is measurable.
#
# AVOID WHEN
#   Python (interpreter overhead swamps the saving), or the array is
#   read-only/shared.
#
# PITFALLS
#   1. The last element MUST be saved and restored, including on the error
#      path. Forgetting is a data-corruption bug, not a wrong answer.
#   2. After restoring, the saved last element must be checked separately —
#      otherwise a target that genuinely lived in the last slot is reported
#      as the sentinel hit.
#   3. It mutates its input. Unsafe on shared or frozen data even though the
#      mutation is temporary.
#
# SEE ALSO    linear_search, bidirectional_linear_search
#
# INTERVIEW
#   - Micro-optimisation reasoning; loop-invariant removal
# --- end curriculum ---

from typing import Any


def sentinel_search(arr: list[Any], target: Any) -> int:
    """
    Sentinel Linear Search.

    Places the target as a sentinel at the end of the list, so the loop
    only needs to check arr[i] == target, not index bounds at every step.

    Args:
        arr (List[Any]): The array to search.
        target (Any): The value to find.

    Returns:
        int: Index of first occurrence of target, or -1 if not found.

    Time Complexity: O(n)
    Space Complexity: O(1)
    """
    n = len(arr)
    if n == 0:
        return -1  # Edge case: empty array

    last = arr[-1]           # Save the last element to restore later
    arr[-1] = target         # Set the sentinel

    i = 0
    # No need to check i < n here!
    while arr[i] != target:
        i += 1

    arr[-1] = last           # Restore original last element

    # Determine if the match was within original array (not just at sentinel)
    if i < n - 1 or arr[-1] == target:
        return i
    return -1
