# --- curriculum: jump_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# JUMP SEARCH  (Searching / advanced)
#
# MENTAL MODEL
#   Step forward in fixed blocks of size sqrt(n) until you overshoot, then
#   linear-scan back through that one block. Optimal block size is sqrt(n),
#   giving O(sqrt n) — worse than binary search but with only forward jumps.
#
# INVARIANT
#   When the jump stops at block boundary b, the target (if present) lies in
#   (b - step, b].
#
# COMPLEXITY  best O(1) | avg O(sqrt n) | worst O(sqrt n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Jumping backwards is expensive or impossible — tape, a singly linked
#   skip structure, or paged storage where a seek costs far more than a
#   sequential read.
#
# AVOID WHEN
#   Ordinary arrays. O(sqrt n) loses badly to O(log n).
#
# PITFALLS
#   1. Block size sqrt(n) is derived by minimising n/m + m; any other
#      constant is worse. Knowing *why* sqrt is the answer is the point.
#   2. The backward scan must stop at the previous block boundary, not run
#      to index 0 — otherwise it degrades to linear search.
#   3. min(step, n) clamping is needed or the last partial block is read out
#      of bounds.
#
# SEE ALSO    binary_search, exponential_search, linear_search
#
# INTERVIEW
#   - Search with only forward traversal
#   - Why sqrt(n)? Derive the optimum
# --- end curriculum ---

import math


def jump_search(arr, target):
    """
    Performs jump search on a sorted array.
    Returns the index if found, else -1.

    Time Complexity: O(sqrt(N))
    Space Complexity: O(1)
    """
    n = len(arr)
    if n == 0:
        return -1

    # Optimal jump size is sqrt(n)
    step = int(math.sqrt(n))
    prev = 0

    # Jump forward until we find a block where arr[prev] <= target <= arr[min(step, n)-1]
    while prev < n and arr[min(step, n) - 1] < target:
        prev = step
        step += int(math.sqrt(n))
        if prev >= n:
            return -1

    # Linear search within the found block
    while prev < min(step, n):
        if arr[prev] == target:
            return prev
        prev += 1

    return -1  # Not found
