# --- curriculum: sublist_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# SUBLIST SEARCH (PATTERN IN LIST)  (Searching / advanced)
#
# MENTAL MODEL
#   Does this sequence appear contiguously inside that one? Anchor at each
#   position in the main list and walk both forward together. The naive
#   O(n*m) version — which is what makes KMP and Rabin-Karp worth learning.
#
# INVARIANT
#   If a match exists starting at index i, the walk from i compares equal
#   for all m pattern elements.
#
# COMPLEXITY  best O(m) | avg O(n*m) | worst O(n*m)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Short patterns, or linked lists where the clever algorithms' index
#   arithmetic does not apply.
#
# AVOID WHEN
#   Long patterns over long text — KMP is O(n+m), Rabin-Karp is O(n+m)
#   expected.
#
# PITFALLS
#   1. The empty pattern should match at index 0 by convention; deciding
#      that explicitly prevents an ambiguous -1.
#   2. The outer loop must stop at n - m, not n, or the inner walk runs off
#      the end.
#   3. Naive matching re-compares characters the previous attempt already
#      examined. Recognising that waste is exactly the insight KMP's failure
#      function exploits.
#
# SEE ALSO    linear_search, trie
#
# INTERVIEW
#   - Implement strStr() (LC 28)
#   - Repeated Substring Pattern (LC 459)
#   - Follow-up: now do it in O(n+m) — KMP
# --- end curriculum ---

"""
Sublist search — find a contiguous pattern inside a larger sequence.

The naive O(n*m) matcher. Its value is as the baseline that motivates KMP and
Rabin-Karp: every time the inner walk fails partway through, it throws away
everything it just learned and restarts one position along. Noticing that waste
is the insight KMP's failure function exploits.
"""

from collections.abc import Sequence
from typing import Any

NOT_FOUND = -1


def sublist_search(main_list: Sequence[Any], pattern: Sequence[Any]) -> int:
    """
    Return the index where `pattern` first appears contiguously in `main_list`,
    or -1 if it does not appear.

    An empty pattern matches at index 0 by convention, the same rule Python's
    str.find follows.

    Time:  O((n - m + 1) * m)
    Space: O(1)

    The inner comparison walks element by element rather than slicing. An earlier
    version compared `main_list[i:i + m] == pattern`, which allocates a fresh
    list of length m on every attempt — and so contradicted its own claim of O(1)
    extra space.
    """
    n, m = len(main_list), len(pattern)

    if m == 0:
        return 0
    if m > n:
        return NOT_FOUND

    for start in range(n - m + 1):
        offset = 0
        while offset < m and main_list[start + offset] == pattern[offset]:
            offset += 1
        if offset == m:
            return start

    return NOT_FOUND


def contains_sublist(main_list: Sequence[Any], pattern: Sequence[Any]) -> bool:
    """
    Whether `pattern` appears contiguously in `main_list`.

    Kept separate from sublist_search because 'where is it' and 'is it there'
    are different questions, and a function that returns a bare bool throws away
    information the caller usually needs next.
    """
    return sublist_search(main_list, pattern) != NOT_FOUND


def all_occurrences(main_list: Sequence[Any], pattern: Sequence[Any]) -> list[int]:
    """
    Every start index at which `pattern` occurs, including overlapping matches.

    Overlap matters: searching [1, 1, 1] for [1, 1] yields [0, 1], not just [0].

    Time:  O((n - m + 1) * m)
    Space: O(number of matches)
    """
    n, m = len(main_list), len(pattern)
    if m == 0 or m > n:
        return []

    found: list[int] = []
    for start in range(n - m + 1):
        offset = 0
        while offset < m and main_list[start + offset] == pattern[offset]:
            offset += 1
        if offset == m:
            found.append(start)
    return found
