# --- curriculum: ternary_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# TERNARY SEARCH  (Searching / advanced)
#
# MENTAL MODEL
#   Split into three parts with two probes instead of two parts with one.
#   Fewer iterations (log base 3) but more comparisons per iteration, so for
#   *sorted array lookup* it is strictly worse than binary search. Its real
#   home is finding the extremum of a unimodal function.
#
# INVARIANT
#   Array form: the target lies in one of the three sub-ranges. Unimodal
#   form: the maximum lies in the retained two-thirds.
#
# COMPLEXITY  best O(1) | avg O(log3 n) iterations, ~2 log3 n comparisons | worst O(log n)
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Maximising or minimising a unimodal function over a range — that is the
#   legitimate use.
#
# AVOID WHEN
#   Sorted array lookup. 2*log3(n) ≈ 1.26*log2(n) comparisons means it does
#   about 26% MORE work than binary search.
#
# PITFALLS
#   1. Believing 'three parts beats two'. Count comparisons, not iterations
#      — binary search wins. This is the classic trap.
#   2. For unimodal optimisation the function must be strictly unimodal; a
#      flat plateau makes the comparison ambiguous and the search can
#      discard the answer.
#   3. Both mid points must be recomputed each iteration from the current
#      window, not carried over.
#
# SEE ALSO    binary_search, fibonacci_search, ubiquitous_binary_search
#
# INTERVIEW
#   - Peak Index in a Mountain Array (LC 852)
#   - Find Peak Element (LC 162)
#   - Why is ternary search slower than binary search?
# --- end curriculum ---

def ternary_search(arr, target):
    """
    Performs ternary search on a sorted array to find the target value.
    Returns the index if found, else -1.

    Time Complexity: O(log₃N)
    Space Complexity: O(1)
    """
    left, right = 0, len(arr) - 1

    while left <= right:
        # Divide the current range into three parts
        third = (right - left) // 3
        mid1 = left + third
        mid2 = right - third

        if arr[mid1] == target:
            return mid1
        if arr[mid2] == target:
            return mid2

        if target < arr[mid1]:
            right = mid1 - 1  # Search in the first third
        elif target > arr[mid2]:
            left = mid2 + 1   # Search in the third third
        else:
            left = mid1 + 1   # Search in the middle third
            right = mid2 - 1

    return -1  # Not found
