# --- curriculum: ubiquitous_binary_search ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# UBIQUITOUS BINARY SEARCH (PREDICATE FORM)  (Searching / advanced)
#
# MENTAL MODEL
#   The general form, and the one worth memorising. Given a monotone
#   predicate over a range (false...false, true...true), find the first
#   true. No array is required — the 'array' can be any answer space. This
#   single shape solves most binary-search interview problems.
#
# INVARIANT
#   predicate(lo - 1) is false and predicate(hi) is true at all times, so
#   the boundary is always inside [lo, hi].
#
# COMPLEXITY  best O(1) | avg O(log(hi - lo)) predicate calls | worst O(log(hi - lo))
# SPACE       O(1)
#
# REACH FOR IT WHEN
#   Anything phrased as 'minimum X such that condition holds' — capacity,
#   speed, threshold, or 'binary search on the answer'.
#
# AVOID WHEN
#   The predicate is not monotone. Then the whole method is invalid, not
#   merely slow.
#
# PITFALLS
#   1. Monotonicity must be verified, not assumed. It is the entire
#      precondition and the usual source of wrong answers.
#   2. Use the half-open form: while lo < hi, mid = lo + (hi-lo)//2, then hi
#      = mid or lo = mid + 1. Mixing in right = mid - 1 loops forever.
#   3. The initial hi must be a value where the predicate is known true — an
#      upper bound on the answer, not the array length.
#
# SEE ALSO    binary_search, rotated_binary_search, ternary_search
#
# INTERVIEW
#   - Koko Eating Bananas (LC 875)
#   - Capacity To Ship Packages (LC 1011)
#   - Split Array Largest Sum (LC 410)
#   - Minimum Number of Days to Make m Bouquets (LC 1482)
#   - Median of Two Sorted Arrays (LC 4)
# --- end curriculum ---

def ubiquitous_binary_search(predicate, lo, hi):
    """
    Finds the minimal value in [lo, hi] such that predicate(value) is True.
    Assumes predicate is monotonic: once True, always True for greater values.

    Returns the minimal value (or hi+1 if not found).
    """
    while lo < hi:
        mid = (lo + hi) // 2
        if predicate(mid):
            hi = mid   # Try lower, keep mid as possible answer
        else:
            lo = mid + 1
    return lo if predicate(lo) else hi + 1  # hi+1 if no solution in range

def min_square_at_least(target):
    def predicate(x):
        return x * x >= target
    # Reasonable upper bound: target (since target*target >= target for target ≥ 1)
    return ubiquitous_binary_search(predicate, 0, target)
