# --- curriculum: bogosort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# BOGOSORT  (Sorting / specialized)
#
# MENTAL MODEL
#   Shuffle at random; check if sorted; repeat. Expected O(n * n!)
#   comparisons. It exists to make the cost of 'generate and test' with no
#   structure viscerally obvious.
#
# INVARIANT
#   None. That is the lesson — the algorithm maintains nothing between
#   iterations.
#
# COMPLEXITY  best O(n) | avg O(n * n!) | worst unbounded
# SPACE       O(1)
# PROPERTIES  stable no  in-place yes  adaptive no
#
# REACH FOR IT WHEN
#   Illustrating expected-versus-worst-case and why unbounded loops need
#   attempt caps.
#
# AVOID WHEN
#   Always. n=12 already exceeds the age of the universe on average.
#
# PITFALLS
#   1. Worst case is genuinely unbounded, not merely large — hence the
#      max_attempts cap in this implementation, which means it can return
#      UNSORTED output. Check the return value.
#   2. Tests must stay under ~8 elements or the suite hangs.
#
# SEE ALSO    stooge_sort, sleep_sort
#
# INTERVIEW
#   - Expected vs worst case analysis
# --- end curriculum ---

import random


def is_sorted(arr):
    """
    Checks if arr is sorted in non-decreasing order.
    """
    for i in range(len(arr) - 1):
        if arr[i] > arr[i + 1]:
            return False
    return True

def bogosort(arr, max_attempts=100000):
    """
    Sorts 'arr' using bogosort (randomly shuffles until sorted).
    max_attempts prevents infinite loops on non-trivial arrays.

    Time Complexity: O((N!) * N) expected
    Space Complexity: O(1) in-place
    """
    attempts = 0
    while not is_sorted(arr) and attempts < max_attempts:
        random.shuffle(arr)
        attempts += 1
    return arr  # Optional, for chaining
