# --- curriculum: cocktail_shaker_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# COCKTAIL SHAKER SORT  (Sorting / specialized)
#
# MENTAL MODEL
#   Bidirectional bubble sort. Sweep left-to-right pushing the max to the
#   end, then right-to-left pulling the min to the front. Fixes bubble
#   sort's 'turtle' problem: a small value near the end needs n passes to
#   walk home in one direction but one pass going back.
#
# INVARIANT
#   After a full forward+backward cycle i, both arr[:i] and arr[n-i:] are
#   final.
#
# COMPLEXITY  best O(n) | avg O(n^2) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable yes  in-place yes  adaptive yes
#
# REACH FOR IT WHEN
#   Nowhere serious. It is the clearest illustration of why traversal
#   direction matters.
#
# AVOID WHEN
#   Production. Still O(n^2); roughly 2x better constant than bubble sort at
#   best.
#
# PITFALLS
#   1. Both bounds must shrink each cycle — shrinking only the upper one
#      re-scans the finished prefix forever.
#   2. The swapped flag must cover both directions, or it exits after a
#      clean forward pass while the backward pass still had work.
#
# SEE ALSO    bubble_sort, gnome_sort, comb_sort
#
# INTERVIEW
#   - Asked as 'how would you improve bubble sort?'
# --- end curriculum ---

def cocktail_shaker_sort(arr):
    """
    Sorts the input list 'arr' in-place using Cocktail Shaker Sort.

    Time Complexity: O(N^2)
    Space Complexity: O(1) (in-place)
    """
    n = len(arr)
    start = 0
    end = n - 1
    swapped = True

    while swapped:
        swapped = False

        # Forward pass (left to right)
        for i in range(start, end):
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                swapped = True

        # If no swaps, array is sorted
        if not swapped:
            break

        swapped = False
        end -= 1  # Last element is now in place

        # Backward pass (right to left)
        for i in range(end - 1, start - 1, -1):
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                swapped = True

        start += 1  # First element is now in place
    return arr  # Optional, for chaining
