# --- curriculum: comb_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# COMB SORT  (Sorting / specialized)
#
# MENTAL MODEL
#   Bubble sort plus shell sort's gap idea. Compare elements a gap apart,
#   shrinking the gap by ~1.3 each pass until it reaches 1. The large early
#   gaps throw small values near the end a long way forward, killing bubble
#   sort's turtles.
#
# INVARIANT
#   After the pass with gap g, arr[i] <= arr[i+g] for all valid i.
#
# COMPLEXITY  best O(n log n) | avg O(n^2 / 2^p) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable no  in-place yes  adaptive yes
#
# REACH FOR IT WHEN
#   You want near-quick-sort speed in ~15 lines with O(1) space and no
#   recursion.
#
# AVOID WHEN
#   Stability required, or you need a provable bound.
#
# PITFALLS
#   1. The 1.3 shrink factor is empirical, not derived. 1.25 or 1.33
#      measurably degrade it.
#   2. The loop must continue while gap > 1 OR a swap happened in the gap-1
#      pass; exiting as soon as gap hits 1 leaves it unsorted.
#   3. Long-range swaps break stability, same as shell sort.
#
# SEE ALSO    shell_sort, bubble_sort, quick_sort
#
# INTERVIEW
#   - Rarely asked; good answer to 'improve bubble sort without recursion'
# --- end curriculum ---

def comb_sort(arr):
    """
    Sorts the input list 'arr' in-place using Comb Sort.

    Time Complexity: O(N^2) worst, O(N log N) average/best (practically faster than bubble sort)
    Space Complexity: O(1) (in-place)
    """
    n = len(arr)
    gap = n
    shrink = 1.3  # Common shrink factor
    swapped = True

    while gap > 1 or swapped:
        # Update the gap for next comb
        gap = int(gap / shrink)
        if gap < 1:
            gap = 1

        swapped = False
        # Compare and swap elements with 'gap' distance
        for i in range(0, n - gap):
            if arr[i] > arr[i + gap]:
                arr[i], arr[i + gap] = arr[i + gap], arr[i]
                swapped = True
    return arr  # Optional, for chaining
