# --- curriculum: gnome_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# GNOME SORT  (Sorting / specialized)
#
# MENTAL MODEL
#   A garden gnome sorting flower pots: look at the pot in front; if it is
#   smaller, swap it back and step backwards, otherwise step forwards. One
#   index, one loop, no nesting. Equivalent to insertion sort done with
#   swaps.
#
# INVARIANT
#   arr[:i] is sorted whenever the index i advances to a new maximum.
#
# COMPLEXITY  best O(n) | avg O(n^2) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable yes  in-place yes  adaptive yes
#
# REACH FOR IT WHEN
#   Demonstrating that a single index and one loop suffice to sort.
#
# AVOID WHEN
#   Production. Insertion sort does the same work with fewer writes.
#
# PITFALLS
#   1. Forgetting to step backward after a swap turns it into a single
#      broken bubble pass.
#   2. The index guard i > 0 must come before the comparison, or the
#      backward step indexes arr[-1] and silently compares the wrong
#      element.
#
# SEE ALSO    insertion_sort, bubble_sort
#
# INTERVIEW
#   - Trivia; occasionally as 'sort with a single loop variable'
# --- end curriculum ---

def gnome_sort(arr):
    """
    Sorts the input list 'arr' in-place using Gnome Sort.

    Time Complexity: O(N^2) worst/average, O(N) best (already sorted)
    Space Complexity: O(1) (in-place)
    Stable: Yes
    """
    n = len(arr)
    index = 0
    while index < n:
        if index == 0 or arr[index] >= arr[index - 1]:
            index += 1
        else:
            arr[index], arr[index - 1] = arr[index - 1], arr[index]
            index -= 1
    return arr  # Optional, for chaining
