# --- curriculum: pancake_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# PANCAKE SORT  (Sorting / specialized)
#
# MENTAL MODEL
#   The only operation allowed is 'flip the top k elements' (reverse a
#   prefix). To place the largest value: flip it to the front, then flip the
#   whole unsorted region so it lands at the back. Two flips per element.
#
# INVARIANT
#   After placing i elements, arr[n-i:] is sorted and final, using at most
#   2i flips.
#
# COMPLEXITY  best O(n) | avg O(n^2) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable no  in-place yes  adaptive no
#
# REACH FOR IT WHEN
#   Whenever the cost model is 'prefix reversal' rather than 'swap' — the
#   classic example of an algorithm shaped by its allowed operation.
#
# AVOID WHEN
#   You are allowed arbitrary swaps. Then it is pointless.
#
# PITFALLS
#   1. The metric is flip *count*, not comparison count. Optimising
#      comparisons here misses the point.
#   2. Finding the max index then flipping twice is 2 flips per element; the
#      known lower bound is ~15n/14, and closing that gap is an open problem
#      (the 'pancake number').
#   3. Flipping the whole array instead of the unsorted prefix undoes
#      already-placed elements.
#
# SEE ALSO    selection_sort, bubble_sort
#
# INTERVIEW
#   - Pancake Sorting (LC 969)
#   - Reverse prefix problems
# --- end curriculum ---

def flip(arr, k):
    """
    Reverses the first k elements of arr in place.
    """
    start = 0
    while start < k:
        arr[start], arr[k] = arr[k], arr[start]
        start += 1
        k -= 1

def pancake_sort(arr):
    """
    Sorts the input list 'arr' in-place using Pancake Sort.

    Time Complexity: O(N^2)
    Space Complexity: O(1) (in-place)
    Stable: No
    """
    n = len(arr)
    for curr_size in range(n, 1, -1):
        # Find index of the maximum element in arr[0:curr_size]
        max_idx = arr.index(max(arr[0:curr_size]))
        if max_idx != curr_size - 1:
            # Bring max to front, if not already at front
            if max_idx != 0:
                flip(arr, max_idx)
            # Now flip the max to its correct position
            flip(arr, curr_size - 1)
    return arr  # Optional, for chaining
