# --- curriculum: sleep_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# SLEEP SORT  (Sorting / specialized)
#
# MENTAL MODEL
#   Spawn a thread per value that sleeps proportionally to the value, then
#   appends itself. The OS scheduler does the ordering. Running time depends
#   on the magnitude of the values, not on how many there are — which
#   disqualifies it as a sorting algorithm.
#
# INVARIANT
#   None that the code enforces. Ordering is delegated to the scheduler, so
#   there is no guarantee at all.
#
# COMPLEXITY  best O(max(arr)) | avg O(max(arr)) | worst unbounded
# SPACE       O(n) threads
# PROPERTIES  stable no  in-place no  adaptive no
#
# REACH FOR IT WHEN
#   Illustrating that 'it produced sorted output' is not proof of
#   correctness.
#
# AVOID WHEN
#   Always. Negative values are impossible and close values race.
#
# PITFALLS
#   1. A tempting 'fix' is to sort the output before returning — which makes
#      the whole function a wrapper around the builtin. This implementation
#      deliberately does not, so the flakiness stays visible.
#   2. Values closer together than scheduler jitter can wake out of order.
#      Raising the time unit trades latency for reliability.
#   3. One OS thread per element: a few thousand values will exhaust thread
#      limits.
#
# SEE ALSO    bogosort, counting_sort
#
# INTERVIEW
#   - Why is this not O(n)?
# --- end curriculum ---

"""
Sleep sort — a joke algorithm that is genuinely instructive.

It offloads ordering to the OS scheduler: spawn one thread per value, each
sleeping for a time proportional to its value, and record values in wake order.
The lesson is that this is *not* a sorting algorithm in any useful sense —
its running time depends on the magnitude of the values rather than on how many
there are, and correctness depends on the scheduler, not on the code.
"""

import threading

DEFAULT_UNIT_SECONDS = 0.01


def sleep_sort(arr: list[float], unit_seconds: float = DEFAULT_UNIT_SECONDS) -> list[float]:
    """
    Return a new list containing the values of `arr` in wake order.

    Each value n sleeps for n * unit_seconds before appending itself. Output is
    ordered only because larger values wake later.

    Time:  O(max(arr) * unit_seconds) wall clock, independent of n
    Space: O(n) threads — one OS thread per element
    Raises ValueError on negative input (a negative sleep is meaningless).

    Correctness caveat: values closer together than the scheduler's timing
    jitter can wake out of order. Raising `unit_seconds` trades latency for
    reliability. This function deliberately does NOT re-sort its output, so the
    flakiness stays visible; an earlier version hid it behind a call to
    sorted(), which made the whole thing a no-op wrapper around the builtin.
    """
    negatives = [n for n in arr if n < 0]
    if negatives:
        raise ValueError(f"sleep_sort requires non-negative values, got {negatives}")

    result: list[float] = []
    lock = threading.Lock()

    def sleeper(value: float) -> None:
        # threading.Event().wait is used instead of time.sleep only because it
        # is the same call the rest of the stdlib uses for interruptible waits.
        threading.Event().wait(value * unit_seconds)
        with lock:
            result.append(value)

    threads = [threading.Thread(target=sleeper, args=(n,)) for n in arr]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    return result
