# --- curriculum: stooge_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# STOOGE SORT  (Sorting / specialized)
#
# MENTAL MODEL
#   Swap the ends if out of order, then recursively sort the first two
#   thirds, the last two thirds, and the first two thirds AGAIN. The repeat
#   is load-bearing — without it the array is not sorted. Complexity
#   O(n^2.71), worse than bubble sort.
#
# INVARIANT
#   After the three recursive calls, arr[lo:hi+1] is sorted. The third call
#   is what restores order disturbed by the second.
#
# COMPLEXITY  best O(n^2.71) | avg O(n^2.71) | worst O(n^2.71)
# SPACE       O(log n)
# PROPERTIES  stable no  in-place yes  adaptive no
#
# REACH FOR IT WHEN
#   Demonstrating that a recurrence can be worse than the obvious quadratic
#   loop.
#
# AVOID WHEN
#   Always.
#
# PITFALLS
#   1. Dropping the third recursive call gives a function that sorts most
#      test inputs and fails on others — a great example of why tests must
#      include adversarial cases.
#   2. The two-thirds split must round *up* (2*(h-l+1)//3) or the recursion
#      does not shrink and never terminates.
#
# SEE ALSO    bogosort, bubble_sort
#
# INTERVIEW
#   - Used to teach Master-theorem recurrence analysis
# --- end curriculum ---

def stooge_sort(arr, low=0, high=None):
    """
    Sorts arr[low..high] using Stooge Sort (in-place).
    Time Complexity: O(N^(log 3 / log 1.5)) ≈ O(N^2.71)
    Space Complexity: O(log N) (recursion stack)
    """
    if high is None:
        high = len(arr) - 1
    if low >= high:
        return arr

    # If first is greater than last, swap
    if arr[low] > arr[high]:
        arr[low], arr[high] = arr[high], arr[low]

    # If there are at least 3 elements
    if high - low + 1 > 2:
        t = (high - low + 1) // 3
        stooge_sort(arr, low, high - t)
        stooge_sort(arr, low + t, high)
        stooge_sort(arr, low, high - t)
    return arr  # Optional, for chaining
