# --- curriculum: disjoint_set ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# DISJOINT SET (UNION-FIND)  (Structures / disjoint set)
#
# MENTAL MODEL
#   Track which elements are in the same group, supporting only two
#   questions: 'same group?' and 'merge these groups'. Each group is a tree
#   whose root names it. Two optimisations — path compression and union by
#   rank — flatten those trees until the cost is indistinguishable from
#   constant.
#
# INVARIANT
#   Every element points toward its set's root; find() returns that root and
#   the root points to itself.
#
# COMPLEXITY  best O(1) | avg O(alpha(n)) ~ O(1) amortised | worst O(log n) without optimisations
# SPACE       O(n)
#
# REACH FOR IT WHEN
#   Connectivity under incremental edge addition, Kruskal's MST, cycle
#   detection in undirected graphs, grid percolation.
#
# AVOID WHEN
#   You need to DELETE edges or split sets — union-find is merge-only by
#   design.
#
# PITFALLS
#   1. Without BOTH path compression and union by rank the trees can become
#      chains and find() degrades to O(n). Either alone gives O(log n);
#      together they give near-constant.
#   2. Union must link ROOT to ROOT. Linking the passed-in elements instead
#      silently creates a structure where find() still works but the depth
#      bound is lost.
#   3. It cannot answer 'are these in different groups *as of step k*' —
#      there is no history. Offline reverse processing is the usual trick.
#   4. Cycle detection only works for UNDIRECTED graphs. Directed cycles
#      need DFS colouring or Kahn's algorithm.
#
# SEE ALSO    undirected_weighted_graph, hashset, undirected_graph
#
# INTERVIEW
#   - Number of Connected Components (LC 323)
#   - Redundant Connection (LC 684)
#   - Accounts Merge (LC 721)
#   - Number of Islands II (LC 305)
#   - Satisfiability of Equality Equations (LC 990)
# --- end curriculum ---

from Linear.arrays import MyArray as Array


class DisjointSet:
    """
    Disjoint Set (Union-Find) Data Structure with optimizations:
    - Path Compression
    - Union by Rank
    """

    def __init__(self, size: int):
        """
        Initialize the disjoint set with `size` elements (0 to size-1).
        Each element is its own parent initially.

        Args:
            size (int): Number of elements in the disjoint set.
        """
        self.n = size
        self.parent = Array()
        self.rank = Array()  # Rank indicates the depth of the tree

        for i in range(size):
            self.parent.append(i)
            self.rank.append(0)

    def _validate(self, x: int):
        """Validate if x is a valid element."""
        if x < 0 or x >= self.n:
            raise ValueError(f"Element {x} is out of bounds (0 to {self.n - 1}).")

    def find(self, x: int) -> int:
        """
        Find the representative (root) of the set containing x.
        Uses Path Compression to flatten the tree.

        Time Complexity: Amortized O(α(n)), nearly constant.
        """
        self._validate(x)
        if self.parent.get(x) != x:
            self.parent.set(x, self.find(self.parent.get(x)))  # Path Compression
        return self.parent.get(x)

    def union(self, x: int, y: int):
        """
        Merge the sets containing x and y.
        Uses Union by Rank to keep the tree shallow.

        Time Complexity: Amortized O(α(n))
        """
        self._validate(x)
        self._validate(y)

        root_x = self.find(x)
        root_y = self.find(y)

        if root_x != root_y:
            # Attach smaller tree under the larger one
            if self.rank.get(root_x) < self.rank.get(root_y):
                self.parent.set(root_x, root_y)
            elif self.rank.get(root_x) > self.rank.get(root_y):
                self.parent.set(root_y, root_x)
            else:
                self.parent.set(root_y, root_x)
                self.rank.set(root_x, self.rank.get(root_x) + 1)

    def connected(self, x: int, y: int) -> bool:
        """
        Check if elements x and y are in the same set.

        Time Complexity: O(α(n))
        """
        return self.find(x) == self.find(y)

    def count_sets(self) -> int:
        """
        Count how many disjoint sets currently exist.
        """
        roots = set()
        for i in range(self.n):
            roots.add(self.find(i))
        return len(roots)

    def __len__(self):
        return self.n

    def __str__(self):
        return "Parents: " + ", ".join(str(self.parent.get(i)) for i in range(self.n))

    def __repr__(self):
        return f"DisjointSet(size={self.n})"
