# --- curriculum: cartesian_tree_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# CARTESIAN TREE SORT  (Sorting / tree-based)
#
# MENTAL MODEL
#   Build a tree that is a min-heap by value AND reproduces the original
#   array on an inorder walk. Then selection-sort through a priority queue
#   seeded with the root, pushing a node's children when it is popped. The
#   heap only holds the current frontier.
#
# INVARIANT
#   Tree: heap-ordered by value, inorder == input order. Extraction: the
#   frontier heap always contains the minimum of every not-yet-emitted
#   subtree root.
#
# COMPLEXITY  best O(n) | avg O(n log n) | worst O(n log n)
# SPACE       O(n)
# PROPERTIES  stable no  in-place no  adaptive yes
#
# REACH FOR IT WHEN
#   Input has long pre-sorted runs — cost is O(n log k) for k runs,
#   approaching O(n) on sorted data.
#
# AVOID WHEN
#   Uniformly random data: tim sort is adaptive too and has far better
#   constants.
#
# PITFALLS
#   1. An inorder traversal of a Cartesian tree returns the ORIGINAL array —
#      that is its defining property. A previous version of this file did
#      inorder then called sorted() on the result, making the whole thing
#      theatre around the builtin.
#   2. The O(n) build is amortised via the stack: each node is pushed and
#      popped at most once. Re-scanning the spine per element makes it
#      O(n^2).
#   3. The priority queue must hold (value, tiebreak, node) so equal values
#      never force a comparison of two nodes.
#
# SEE ALSO    tree_sort, min_heap, tim_sort, quick_sort
#
# INTERVIEW
#   - Largest Rectangle in Histogram (LC 84) — same monotonic-stack build
#   - Maximum Binary Tree (LC 654) — literally a Cartesian tree
#   - Treaps: BST by key, heap by priority
# --- end curriculum ---

"""
Cartesian tree sort — adaptive O(n log n) that exploits existing runs.

The defining property of a Cartesian tree is that an inorder traversal
reproduces the *original* array, while the values obey the min-heap property.
So inorder alone does not sort: the sorting work is the heap-ordered extraction
that follows.
"""


from Non_Linear.heaps.min_heap import MinHeap


class TreeNode:
    """Node of a min-heap Cartesian tree."""

    __slots__ = ("val", "left", "right")

    def __init__(self, val) -> None:
        self.val = val
        self.left: TreeNode | None = None
        self.right: TreeNode | None = None


def build_cartesian_tree(arr: list) -> TreeNode | None:
    """
    Build a min-heap Cartesian tree from `arr` in O(n) total time.

    Walk left to right maintaining a stack of nodes on the tree's right spine.
    For a new value, pop every spine node larger than it — the last one popped
    becomes the new node's left child, and the new node becomes the right child
    of whatever remains on top. Each node is pushed and popped at most once,
    which is where the linear bound comes from.

    Time:  O(n) amortised
    Space: O(n)
    """
    if not arr:
        return None

    stack: list[TreeNode] = []
    for num in arr:
        curr = TreeNode(num)
        last_popped = None
        while stack and stack[-1].val > num:
            last_popped = stack.pop()
        curr.left = last_popped
        if stack:
            stack[-1].right = curr
        stack.append(curr)

    return stack[0]


def inorder_traversal(root: TreeNode | None, out: list) -> list:
    """
    Append the inorder sequence of `root` to `out`.

    For a Cartesian tree this returns the *original* array, not a sorted one.
    Kept because seeing that for yourself is the point of the structure.

    Time:  O(n)
    Space: O(h) recursion stack
    """
    if root is not None:
        inorder_traversal(root.left, out)
        out.append(root.val)
        inorder_traversal(root.right, out)
    return out


def cartesian_tree_sort(arr: list) -> list:
    """
    Sort `arr` and return a new list, using Cartesian tree sort.

    Build the Cartesian tree, then run a selection sort through a priority
    queue seeded with the root: pop the minimum, emit it, and push its two
    children. The heap only ever holds nodes on the current frontier, so its
    size is bounded by the number of ascending runs in the input — which is
    what makes this adaptive.

    Time:  O(n log n) worst case; O(n log k) for k ascending runs;
           O(n) on already-sorted input (frontier stays size 1)
    Space: O(n) for the tree plus O(k) for the frontier heap

    Uses this project's own MinHeap rather than heapq.
    """
    root = build_cartesian_tree(arr)
    if root is None:
        return []

    # Tuples are (value, tiebreak, node). The monotonically increasing tiebreak
    # keeps equal values in a deterministic order and stops the heap from ever
    # needing to compare two TreeNode objects.
    frontier = MinHeap()
    tiebreak = 0
    frontier.insert((root.val, tiebreak, root))

    result: list = []
    while len(frontier) > 0:
        _, _, node = frontier.extract_min()
        result.append(node.val)
        for child in (node.left, node.right):
            if child is not None:
                tiebreak += 1
                frontier.insert((child.val, tiebreak, child))

    return result
