# --- curriculum: tree_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# TREE SORT  (Sorting / tree-based)
#
# MENTAL MODEL
#   Insert everything into a binary search tree, then read it back with an
#   inorder traversal. The BST's ordering invariant does the sorting; the
#   traversal just reports it.
#
# INVARIANT
#   The BST property (left < node <= right) holds after every insert, so
#   inorder yields sorted output.
#
# COMPLEXITY  best O(n log n) | avg O(n log n) | worst O(n^2)
# SPACE       O(n)
# PROPERTIES  stable no  in-place no  adaptive no
#
# REACH FOR IT WHEN
#   You need the sorted structure to stay queryable afterwards — supports
#   later insert, delete, predecessor, range queries.
#
# AVOID WHEN
#   You only need a sorted list once. The tree's pointer overhead and cache
#   behaviour lose badly to quick sort.
#
# PITFALLS
#   1. Sorted input builds a degenerate linked list: O(n^2) time and O(n)
#      recursion depth. A self-balancing tree (AVL, red-black) fixes it.
#   2. Recursive inorder traversal overflows the stack on that degenerate
#      shape; an explicit stack or Morris traversal does not.
#   3. Duplicate handling must be decided explicitly — dropping them makes
#      it a set, not a sort.
#
# SEE ALSO    bst, cartesian_tree_sort, traversals, heap_sort
#
# INTERVIEW
#   - Kth Smallest Element in a BST (LC 230)
#   - Validate BST (LC 98)
#   - Count of Smaller Numbers After Self (LC 315)
# --- end curriculum ---

class TreeNode:
    def __init__(self, val):
        self.val = val
        self.left = None
        self.right = None

def insert(root, val):
    """Insert a value into BST (allows duplicates on right)."""
    if root is None:
        return TreeNode(val)
    if val < root.val:
        root.left = insert(root.left, val)
    else:
        root.right = insert(root.right, val)
    return root

def inorder_traversal(root, res):
    """Append the in-order traversal of BST to res."""
    if root:
        inorder_traversal(root.left, res)
        res.append(root.val)
        inorder_traversal(root.right, res)

def tree_sort(arr):
    """
    Sorts a list using Tree Sort (BST).
    Time Complexity: O(N log N) average, O(N^2) worst (unbalanced)
    Space Complexity: O(N) for tree
    Stable: No (BST does not preserve order of duplicates)
    """
    root = None
    for num in arr:
        root = insert(root, num)
    result = []
    inorder_traversal(root, result)
    return result
