# --- curriculum: bitonic_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# BITONIC SORT  (Sorting / network)
#
# MENTAL MODEL
#   A *fixed* comparison network: which pairs get compared is decided in
#   advance, never by the data. Build a bitonic sequence (one that rises
#   then falls) by sorting one half up and the other down, then merge it
#   with a recursive half-cleaner.
#
# INVARIANT
#   After a half-cleaner on a bitonic sequence of length c, every value in
#   the first half is <= every value in the second, and both halves are
#   themselves bitonic.
#
# COMPLEXITY  best O(n log^2 n) | avg O(n log^2 n) | worst O(n log^2 n)
# SPACE       O(log n)
# PROPERTIES  stable no  in-place yes  adaptive no
#
# REACH FOR IT WHEN
#   Hardware sorting networks and GPUs: O(log^2 n) *depth* with a
#   data-independent schedule, which is what lets it be baked into silicon
#   or run branch-free.
#
# AVOID WHEN
#   Sequentially — it does more comparisons than merge sort for no benefit.
#
# PITFALLS
#   1. The network only exists for power-of-two lengths. Feeding it n=5 used
#      to return a silently WRONG result here; it now pads with infinities
#      and truncates.
#   2. Data-independence is the point: it performs the same comparisons on
#      sorted and reversed input, so it cannot be adaptive.
#   3. The merge direction parameter must be threaded through the recursion;
#      hardcoding ascending makes the descending half wrong.
#
# SEE ALSO    odd_even_sort, merge_sort
#
# INTERVIEW
#   - Design a sorting network
#   - Branch-free / constant-time sorting
# --- end curriculum ---

"""Bitonic sort — a fixed comparison network, not a data-dependent algorithm."""

import math

ASCENDING = 1
DESCENDING = 0


def bitonic_merge(arr: list[float], low: int, cnt: int, direction: int) -> None:
    """
    Merge the bitonic sequence arr[low : low + cnt] into sorted order.

    A *bitonic* sequence rises then falls (or is a rotation of such). The
    half-cleaner below compares element i with element i + cnt//2 for every i
    in the first half; afterwards every value in the first half is <= every
    value in the second half, and both halves are themselves bitonic. Recurse.

    Requires cnt to be a power of two.

    Time:  O(log^2 n) network depth, O(n log n) comparators
    Space: O(log n) recursion stack
    """
    if cnt <= 1:
        return

    k = cnt // 2
    for i in range(low, low + k):
        ascending_out_of_order = direction == ASCENDING and arr[i] > arr[i + k]
        descending_out_of_order = direction == DESCENDING and arr[i] < arr[i + k]
        if ascending_out_of_order or descending_out_of_order:
            arr[i], arr[i + k] = arr[i + k], arr[i]

    bitonic_merge(arr, low, k, direction)
    bitonic_merge(arr, low + k, k, direction)


def bitonic_sort_network(arr: list[float], low: int, cnt: int, direction: int) -> None:
    """
    Sort arr[low : low + cnt] in place using the pure bitonic network.

    Builds a bitonic sequence by sorting the first half ascending and the
    second half descending, then merges it.

    Requires cnt to be a power of two. Callers with arbitrary lengths should
    use bitonic_sort(), which pads.
    """
    if cnt <= 1:
        return

    k = cnt // 2
    bitonic_sort_network(arr, low, k, ASCENDING)
    bitonic_sort_network(arr, low + k, k, DESCENDING)
    bitonic_merge(arr, low, cnt, direction)


def bitonic_sort(arr: list[float], direction: int = ASCENDING) -> list[float]:
    """
    Sort `arr` in place with bitonic sort, for any length.

    The underlying network only exists for power-of-two sizes, so a shorter
    list is padded up to the next power of two with sentinels that are
    guaranteed to land at the end, then truncated back.

    Time:  O(n log^2 n) comparisons
    Space: O(n) for the padded working copy when n is not a power of two
    """
    n = len(arr)
    if n <= 1:
        return arr

    padded_size = 1 << (n - 1).bit_length()

    if padded_size == n:
        bitonic_sort_network(arr, 0, n, direction)
        return arr

    # Pad with a sentinel that sorts to the far end in the chosen direction,
    # so the real values occupy a contiguous prefix after the network runs.
    sentinel = math.inf if direction == ASCENDING else -math.inf
    work = list(arr) + [sentinel] * (padded_size - n)
    bitonic_sort_network(work, 0, padded_size, direction)
    arr[:] = work[:n]
    return arr
