# --- curriculum: brick_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# BRICK SORT  (Sorting / network)
#
# MENTAL MODEL
#   Another name for odd-even transposition sort — the alternating
#   comparison pairs look like a brick wall's offset courses. Kept as a
#   separate file because both names appear in the literature and you should
#   recognise either.
#
# INVARIANT
#   Identical to odd-even sort: alternating independent compare-exchange
#   phases.
#
# COMPLEXITY  best O(n) | avg O(n^2) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable yes  in-place yes  adaptive yes
#
# REACH FOR IT WHEN
#   Same as odd-even sort. The name is the only difference.
#
# AVOID WHEN
#   Same as odd-even sort.
#
# PITFALLS
#   1. Being asked for 'brick sort' and not recognising it as odd-even sort
#      is the only real trap here.
#
# SEE ALSO    odd_even_sort, bitonic_sort
#
# INTERVIEW
#   - Terminology recognition only
# --- end curriculum ---

def brick_sort(arr):
    """
    Sorts the input list 'arr' in-place using Brick Sort (Odd-Even Sort).

    Time Complexity: O(N^2)
    Space Complexity: O(1) (in-place)
    Stable: Yes
    """
    n = len(arr)
    is_sorted = False

    while not is_sorted:
        is_sorted = True

        # Odd indexed pass
        for i in range(1, n - 1, 2):
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                is_sorted = False

        # Even indexed pass
        for i in range(0, n - 1, 2):
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                is_sorted = False

    return arr  # Optional, for chaining
