# --- curriculum: odd_even_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# ODD-EVEN TRANSPOSITION SORT  (Sorting / network)
#
# MENTAL MODEL
#   Bubble sort restructured for parallel hardware. Alternate between
#   comparing all (odd, even) neighbour pairs and all (even, odd) pairs.
#   Within one phase no pair shares an element, so every comparison in that
#   phase can run simultaneously.
#
# INVARIANT
#   After n phases the array is sorted; each phase is a set of independent
#   compare-exchanges.
#
# COMPLEXITY  best O(n) | avg O(n^2) | worst O(n^2)
# SPACE       O(1)
# PROPERTIES  stable yes  in-place yes  adaptive yes
#
# REACH FOR IT WHEN
#   SIMD, GPU, or systolic arrays — n processors give O(n) depth.
#
# AVOID WHEN
#   Single-threaded code. It is strictly worse than bubble sort there.
#
# PITFALLS
#   1. The sequential version looks pointlessly slow; its value is the
#      *dependency structure*, which is invisible in a single-threaded
#      reading.
#   2. The loop must keep alternating until a full odd AND even phase both
#      make no swaps — stopping after one clean phase leaves it unsorted.
#   3. Index bounds differ per phase: start at 1 for odd, 0 for even, and
#      both must stop at n-1.
#
# SEE ALSO    brick_sort, bitonic_sort, bubble_sort
#
# INTERVIEW
#   - How would you sort on a GPU?
# --- end curriculum ---

def odd_even_sort(arr):
    """
    Sorts the input list 'arr' in-place using Odd-Even (Brick) Sort.

    Time Complexity: O(N^2)
    Space Complexity: O(1) (in-place)
    Stable: Yes
    """
    n = len(arr)
    is_sorted = False

    while not is_sorted:
        is_sorted = True

        # Perform Bubble sort on odd indexed elements
        for i in range(1, n - 1, 2):
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                is_sorted = False

        # Perform Bubble sort on even indexed elements
        for i in range(0, n - 1, 2):
            if arr[i] > arr[i + 1]:
                arr[i], arr[i + 1] = arr[i + 1], arr[i]
                is_sorted = False
    return arr  # Optional, for chaining
