# --- curriculum: astar ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# A* TREE SEARCH  (Searching / tree)
#
# MENTAL MODEL
#   Best-first search ordered by f = g + h: g is the cost already paid, h is
#   an estimate of the cost remaining. Pure g is Dijkstra; pure h is greedy
#   best-first; A* is the combination, and the heuristic is what lets it
#   ignore most of the search space.
#
# INVARIANT
#   If h never overestimates the true remaining cost (admissible), the first
#   time the goal is popped, its path is optimal.
#
# COMPLEXITY  best O(b*d) | avg O(b^d) worst | worst O(b^d)
# SPACE       O(b^d) frontier
#
# REACH FOR IT WHEN
#   Pathfinding with a usable distance estimate — grids, maps, games, puzzle
#   solving.
#
# AVOID WHEN
#   No meaningful heuristic exists (then it is just Dijkstra with overhead),
#   or the graph is tiny.
#
# PITFALLS
#   1. An inadmissible heuristic (one that overestimates) breaks the
#      optimality guarantee — you still get an answer, just not the best
#      one, silently.
#   2. Heap entries must carry a tiebreaker counter so equal f-scores never
#      force a comparison of two node objects (TypeError in Python 3).
#   3. On a general graph A* also needs consistency/monotonicity of h, or a
#      closed set with re-opening. On a tree each node has one path, which
#      is why this tree-only version is simpler.
#   4. h = 0 reduces it to Dijkstra. Useful sanity check when debugging a
#      suspicious heuristic.
#
# SEE ALSO    min_heap, directed_weighted_graph, undirected_weighted_graph, traversals
#
# INTERVIEW
#   - Network Delay Time (LC 743) — Dijkstra
#   - Shortest Path in Binary Matrix (LC 1091)
#   - Sliding Puzzle (LC 773)
#   - When does A* degenerate to Dijkstra or to BFS?
# --- end curriculum ---

import heapq
from collections.abc import Callable
from itertools import count
from typing import Any


class TreeNode:
    def __init__(self, value: Any, children: list['TreeNode'] = None, cost: float = 1.0):
        self.value = value
        self.children = children or []  # List of child TreeNodes
        self.cost = cost                # Cost from parent to this node (default 1.0)

    def __repr__(self):
        return f"TreeNode({self.value})"

    def __hash__(self):
        # Needed for use in dictionaries (for came_from, g_score)
        return hash(id(self))

def astar_tree_search(
    start: TreeNode,
    goal_fn: Callable[[TreeNode], bool],
    heuristic_fn: Callable[[TreeNode], float],
) -> list[TreeNode] | None:
    """
    A* Search algorithm for trees.

    Args:
        start: The starting TreeNode.
        goal_fn: Function that returns True if a node is the goal.
        heuristic_fn: Function estimating cost from a node to the goal.

    Returns:
        List[TreeNode]: Path from start to goal (inclusive), or None if not found.
    """
    open_list: list[tuple[float, float, int, TreeNode]] = []
    tie_breaker = count()  # Unique counter for heap tuple (solves heapq comparison issue)

    # Heap stores: (f_score, g_score, tie_breaker, node)
    heapq.heappush(open_list, (heuristic_fn(start), 0, next(tie_breaker), start))
    came_from: dict[TreeNode, TreeNode | None] = {start: None}
    g_score: dict[TreeNode, float] = {start: 0}

    while open_list:
        f, g, _, current = heapq.heappop(open_list)

        if goal_fn(current):
            # Reconstruct the path from start to goal
            path = []
            while current:
                path.append(current)
                current = came_from[current]
            return path[::-1]  # Reverse to get path from start to goal

        for child in current.children:
            tentative_g = g_score[current] + child.cost
            if child not in g_score or tentative_g < g_score[child]:
                came_from[child] = current
                g_score[child] = tentative_g
                f_score = tentative_g + heuristic_fn(child)
                # Always add a unique counter so TreeNodes are never directly compared
                heapq.heappush(open_list, (f_score, tentative_g, next(tie_breaker), child))
    return None
