"""
Generate INDEX.md and the in-file teaching headers from the curriculum.

    python -m Utils.sync            # write everything
    python -m Utils.sync --check    # fail if anything is out of date (CI)
    python -m Utils.sync --index    # INDEX.md only
    python -m Utils.sync --headers  # in-file headers only

The headers live between two marker comments, so running this repeatedly is
idempotent and never touches the code below. Edit `curriculum/`, re-run this,
and the index, the headers and the drill prompts all move together.
"""

import argparse
import pathlib
import sys
from collections.abc import Sequence

import curriculum
from curriculum.schema import Topic

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX_PATH = REPO_ROOT / "INDEX.md"

HEADER_START = "# --- curriculum:"
HEADER_END = "# --- end curriculum ---"
HEADER_NOTE = "generated by `python -m Utils.sync` from curriculum/ -- edit there, not here"
WRAP_WIDTH = 76


def wrap(text: str, indent: str = "#   ") -> list[str]:
    """Hard-wrap `text` into comment lines at WRAP_WIDTH."""
    words = text.split()
    lines: list[str] = []
    current = indent
    for word in words:
        candidate = f"{current} {word}" if current.strip() != indent.strip() else f"{indent}{word}"
        if len(candidate) > WRAP_WIDTH and current.strip() != indent.strip():
            lines.append(current)
            current = f"{indent}{word}"
        else:
            current = candidate
    if current.strip() != indent.strip():
        lines.append(current)
    return lines


def render_header(topic: Topic) -> str:
    """Build the comment block for one topic."""
    c = topic.complexity
    lines = [
        f"{HEADER_START} {topic.slug} ---",
        f"# {HEADER_NOTE}",
        "#",
        f"# {topic.name.upper()}  ({topic.family})",
        "#",
        "# MENTAL MODEL",
        *wrap(topic.mental_model),
        "#",
        "# INVARIANT",
        *wrap(topic.invariant),
        "#",
        f"# COMPLEXITY  best {c.best} | avg {c.average} | worst {c.worst}",
        f"# SPACE       {c.space}",
    ]

    flags = topic.flag_summary()
    if flags != "—":
        lines.append(f"# PROPERTIES  {flags}")

    lines += [
        "#",
        "# REACH FOR IT WHEN",
        *wrap(topic.use_when),
        "#",
        "# AVOID WHEN",
        *wrap(topic.avoid_when),
    ]

    if topic.pitfalls:
        lines += ["#", "# PITFALLS"]
        for i, pitfall in enumerate(topic.pitfalls, start=1):
            body = wrap(pitfall, indent="#      ")
            body[0] = f"#   {i}. " + body[0].lstrip("# ").lstrip()
            lines += body

    if topic.see_also:
        lines += ["#", f"# SEE ALSO    {', '.join(topic.see_also)}"]
    if topic.interview:
        lines += ["#", "# INTERVIEW"]
        lines += [f"#   - {problem}" for problem in topic.interview]
    if topic.doc:
        lines += ["#", f"# LONGER NOTE {topic.doc}"]

    lines += [HEADER_END, ""]
    return "\n".join(lines) + "\n"


def strip_existing_header(text: str) -> str:
    """Remove a previously generated block, leaving everything else intact."""
    if HEADER_START not in text:
        return text
    lines = text.splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith(HEADER_START))
    try:
        end = next(i for i, line in enumerate(lines) if line.startswith(HEADER_END))
    except StopIteration:
        # Truncated block (hand-edited?). Drop from the start marker to the first
        # line that is not a comment, which is the safest recoverable boundary.
        end = start
        while end + 1 < len(lines) and lines[end + 1].startswith("#"):
            end += 1
    remaining = lines[:start] + lines[end + 1:]
    while remaining and not remaining[0].strip():
        remaining.pop(0)
    return "\n".join(remaining) + "\n"


def render_headers(topics: Sequence[Topic]) -> str:
    """
    Build the block for every topic that lives in one file.

    More than one Topic can share an entry file — binary_tree.py carries both
    `binary_tree` and `binary_tree_lca` — so their headers are stacked rather
    than overwriting each other, which is what made an earlier version of this
    function oscillate between two outputs on repeated runs.
    """
    return "".join(render_header(t) for t in topics)


def strip_all_headers(text: str) -> str:
    """Remove every generated block from `text`."""
    while HEADER_START in text:
        stripped = strip_existing_header(text)
        if stripped == text:
            break
        text = stripped
    return text


def topics_by_path() -> list[tuple[str, list[Topic]]]:
    """Group topics by the entry file they annotate, preserving curriculum order."""
    grouped: dict = {}
    for topic in curriculum.ALL_TOPICS:
        grouped.setdefault(topic.path, []).append(topic)
    return list(grouped.items())


def expected_file_text(path: pathlib.Path, topics: Sequence[Topic]) -> str:
    """What `path` should contain once headers are in sync."""
    return render_headers(topics) + strip_all_headers(path.read_text(encoding="utf-8"))


def sync_headers(check: bool = False) -> tuple[int, list[str]]:
    """
    Refresh the header block of every annotated file.

    The block is comments only, so it can precede a module docstring without
    stopping that docstring from being the module's __doc__ — comments are not
    statements.
    """
    changed: list[str] = []
    for rel_path, topics in topics_by_path():
        path = REPO_ROOT / rel_path
        if not path.exists():
            changed.append(f"{rel_path} (MISSING)")
            continue
        current = path.read_text(encoding="utf-8")
        expected = expected_file_text(path, topics)
        if current == expected:
            continue
        changed.append(rel_path)
        if not check:
            path.write_text(expected, encoding="utf-8")
    return len(changed), sorted(changed)


def _doc_cell(topic: Topic) -> str:
    return f"[note]({topic.doc})" if topic.doc else "—"


def render_index() -> str:
    """Build INDEX.md: one row per topic, grouped by family."""
    total = len(curriculum.ALL_TOPICS)
    out = [
        "# INDEX",
        "",
        f"All {total} concepts in the lab, one row each. Generated by "
        "`python -m Utils.sync` from `curriculum/` — do not edit by hand.",
        "",
        "The **Reach for it when** column is the one to read during revision: "
        "complexity tells you what something costs, that column tells you why "
        "you would ever pick it.",
        "",
        "Drill any row with `python drill.py --topic <slug>`.",
        "",
    ]

    for family in curriculum.families():
        topics = [t for t in curriculum.ALL_TOPICS if t.family == family]
        out += [
            f"## {family}",
            "",
            "| Concept | slug | Code | Note | best / avg / worst | Space | Properties | Reach for it when |",
            "|---|---|---|---|---|---|---|---|",
        ]
        for t in topics:
            props = t.flag_summary().replace("  ", ", ")
            out.append(
                f"| {t.name} | `{t.slug}` | [{t.path.split('/')[-1]}]({t.path}) "
                f"| {_doc_cell(t)} | {t.complexity.as_row()} | {t.complexity.space} "
                f"| {props} | {t.use_when} |"
            )
        out.append("")

    out += [
        "## Cross-reference map",
        "",
        "Concepts that explain each other. Following these beats reading rows "
        "top to bottom, because the links are where the transferable ideas live.",
        "",
    ]
    for t in curriculum.ALL_TOPICS:
        if t.see_also:
            links = ", ".join(f"`{s}`" for s in t.see_also)
            out.append(f"- `{t.slug}` -> {links}")
    out.append("")

    return "\n".join(out)


def sync_index(check: bool = False) -> bool:
    """Write INDEX.md. Returns True if it changed (or would change)."""
    expected = render_index()
    current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
    if current == expected:
        return False
    if not check:
        INDEX_PATH.write_text(expected, encoding="utf-8")
    return True


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m Utils.sync",
        description="Regenerate INDEX.md and the in-file teaching headers from curriculum/.",
    )
    parser.add_argument("--check", action="store_true", help="report drift without writing (CI)")
    parser.add_argument("--index", action="store_true", help="INDEX.md only")
    parser.add_argument("--headers", action="store_true", help="in-file headers only")
    args = parser.parse_args(argv)

    do_index = args.index or not args.headers
    do_headers = args.headers or not args.index

    stale: list[str] = []

    if do_index and sync_index(check=args.check):
        stale.append("INDEX.md")
        print(f"{'stale' if args.check else 'wrote'}: INDEX.md")

    if do_headers:
        count, paths = sync_headers(check=args.check)
        if count:
            stale += paths
            verb = "stale" if args.check else "updated"
            print(f"{verb}: {len(paths)} file(s)")
            for p in paths:
                print(f"    {p}")

    if not stale:
        print("everything already in sync")
        return 0

    if args.check:
        print(
            "\nOut of sync with curriculum/. Run `python -m Utils.sync` and commit the result.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
