# --- curriculum: heap_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# HEAP SORT  (Sorting / efficient)
#
# MENTAL MODEL
#   Selection sort where the 'find the max' step is O(log n) instead of
#   O(n), because the unsorted region is kept as a max-heap. Build the heap
#   in O(n), then repeatedly swap the root to the back and sift down over a
#   region one shorter.
#
# INVARIANT
#   arr[:heap_size] satisfies the max-heap property and arr[heap_size:] is
#   sorted and final.
#
# COMPLEXITY  best O(n log n) | avg O(n log n) | worst O(n log n)
# SPACE       O(1)
# PROPERTIES  stable no  in-place yes  adaptive no
#
# REACH FOR IT WHEN
#   You need a hard O(n log n) ceiling with O(1) space — embedded,
#   real-time, or as introsort's bail-out when quick sort goes bad.
#
# AVOID WHEN
#   Throughput matters on ordinary data: its memory access jumps around the
#   array, so it loses to quick sort on cache despite equal asymptotics.
#
# PITFALLS
#   1. Build the heap bottom-up from n//2 - 1 down to 0 — that is O(n).
#      Inserting n elements one at a time is O(n log n) and throws away the
#      cheap build.
#   2. The sift-down during the extraction phase must be bounded by the
#      shrinking heap size, not len(arr), or it pulls sorted values back
#      into the heap.
#   3. Child indices are 2i+1 and 2i+2 for 0-based arrays; the 2i/2i+1 form
#      is for 1-based and mixing them corrupts the heap silently.
#
# SEE ALSO    min_heap, max_heap, selection_sort, intro_sort
#
# INTERVIEW
#   - Kth Largest Element in a Stream (LC 703)
#   - Merge k Sorted Lists (LC 23)
#   - Find Median from Data Stream (LC 295) — two heaps
# --- end curriculum ---

def heap_sort(arr):
    """
    Sorts the input list 'arr' in-place using Heap Sort.

    Time Complexity: O(N log N)
    Space Complexity: O(1) (in-place, uses array to simulate heap)
    """
    n = len(arr)

    # Build a max heap
    for i in range(n // 2 - 1, -1, -1):
        heapify(arr, n, i)

    # Extract elements from the heap one by one
    for i in range(n - 1, 0, -1):
        # Move current root to end
        arr[0], arr[i] = arr[i], arr[0]
        # Heapify the reduced heap
        heapify(arr, i, 0)
    return arr  # Optional, for chaining

def heapify(arr, n, i):
    """
    Maintains the max heap property for a subtree rooted at index i.
    """
    largest = i      # Initialize largest as root
    left = 2 * i + 1 # left child
    right = 2 * i + 2 # right child

    # If left child exists and is greater than root
    if left < n and arr[left] > arr[largest]:
        largest = left

    # If right child exists and is greater than largest so far
    if right < n and arr[right] > arr[largest]:
        largest = right

    # If largest is not root, swap and continue heapifying
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        heapify(arr, n, largest)
