# --- curriculum: merge_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# MERGE SORT  (Sorting / efficient)
#
# MENTAL MODEL
#   Split in half, sort each half, then merge two sorted lists by repeatedly
#   taking the smaller head. All the work is in the merge; the split is
#   free. Recursion depth log n, each level touches n elements, hence n log
#   n with no bad case.
#
# INVARIANT
#   merge(a, b) emits values in non-decreasing order and, on ties, takes
#   from `a` first — which is exactly why the sort is stable.
#
# COMPLEXITY  best O(n log n) | avg O(n log n) | worst O(n log n)
# SPACE       O(n)
# PROPERTIES  stable yes  in-place no  adaptive no
#
# REACH FOR IT WHEN
#   Stability is required; sorting linked lists (O(1) extra space there);
#   external sorting; any guaranteed-n-log-n requirement.
#
# AVOID WHEN
#   Memory is tight and the data is an array — quick sort is in-place and
#   has a smaller constant.
#
# PITFALLS
#   1. Taking from the right half on ties destroys stability and the bug is
#      invisible on integers — only visible when sorting records.
#   2. Allocating new lists inside the merge at every level is what makes
#      naive implementations slow; a single scratch buffer reused across
#      levels is the standard fix.
#   3. mid = len(arr) // 2 with a base case of len <= 1 — a base case of len
#      == 0 recurses forever on single-element lists.
#
# SEE ALSO    tim_sort, quick_sort, external_merge_sort, polyphase_sort
#
# INTERVIEW
#   - Sort List (LC 148)
#   - Count of Smaller Numbers After Self (LC 315)
#   - Reverse Pairs / inversion counting (LC 493)
#   - Merge k Sorted Lists (LC 23)
# --- end curriculum ---

def merge_sort(arr):
    """
    Sorts the input list 'arr' using Merge Sort (recursive, not in-place).
    Returns a new sorted list.

    Time Complexity: O(N log N)
    Space Complexity: O(N) (additional arrays for merging)
    """
    if len(arr) <= 1:
        return arr  # Base case: already sorted

    mid = len(arr) // 2
    # Recursively sort left and right halves
    left = merge_sort(arr[:mid])
    right = merge_sort(arr[mid:])

    # Merge the sorted halves
    return merge(left, right)

def merge(left, right):
    """
    Merges two sorted lists into one sorted list.
    """
    merged = []
    i = j = 0
    # Merge until one side runs out
    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            merged.append(left[i])
            i += 1
        else:
            merged.append(right[j])
            j += 1
    # Add any remaining elements
    merged.extend(left[i:])
    merged.extend(right[j:])
    return merged
