# --- curriculum: quick_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# QUICK SORT  (Sorting / efficient)
#
# MENTAL MODEL
#   Pick a pivot and partition so that smaller values sit left and larger
#   right. The pivot is now in its final position — permanently. Recurse on
#   both sides. There is no merge step: the partition *is* the work.
#
# INVARIANT
#   After partition(lo, hi) returns p: arr[p] is final, arr[lo:p] <= arr[p]
#   <= arr[p+1:hi+1].
#
# COMPLEXITY  best O(n log n) | avg O(n log n) | worst O(n^2)
# SPACE       O(log n)
# PROPERTIES  stable no  in-place yes  adaptive no
#
# REACH FOR IT WHEN
#   Default for in-memory arrays. Lower constant factor than merge sort and
#   sequential memory access that the cache likes.
#
# AVOID WHEN
#   Worst-case latency matters (use heap sort or introsort), or stability is
#   required (use merge/tim sort).
#
# PITFALLS
#   1. Already-sorted input with a first- or last-element pivot gives O(n^2)
#      time AND O(n) recursion depth — a stack overflow, not just slowness.
#      Random or median-of-3 pivot defends against it.
#   2. Lomuto and Hoare partition schemes return different things; copying a
#      recursion line from one into the other loops forever.
#   3. Recursing on [lo, p] instead of [lo, p-1] never shrinks the range
#      when the pivot lands at p == lo.
#   4. Arrays of all-equal values degrade to O(n^2) under Lomuto; three-way
#      (Dutch national flag) partitioning fixes it.
#
# SEE ALSO    intro_sort, merge_sort, heap_sort, bucket_sort
#
# INTERVIEW
#   - Kth Largest Element in an Array (LC 215) — quickselect
#   - Sort Colors (LC 75) — three-way partition
#   - Wiggle Sort II (LC 324)
#   - Top K Frequent Elements (LC 347)
# --- end curriculum ---

def quick_sort(arr, low=0, high=None):
    """
    Sorts the input list 'arr' in-place using Quick Sort (Lomuto partition scheme).

    Time Complexity: O(N log N) average, O(N^2) worst-case
    Space Complexity: O(log N) average (due to recursion stack)
    """
    if high is None:
        high = len(arr) - 1
    if low < high:
        # Partition the array
        p = partition(arr, low, high)
        # Recursively sort elements before and after partition
        quick_sort(arr, low, p - 1)
        quick_sort(arr, p + 1, high)
    return arr  # Optional, for chaining

def partition(arr, low, high):
    """
    Lomuto partitioning:
    Picks the last element as pivot, places it at correct sorted position,
    and places all smaller elements to left of pivot and all greater to right.
    """
    pivot = arr[high]
    i = low - 1  # Place for smaller element
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]  # Swap
    # Place pivot in the right position
    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    return i + 1
