# --- curriculum: intro_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# INTRO SORT  (Sorting / advanced)
#
# MENTAL MODEL
#   Quick sort with two escape hatches. Below a size threshold, switch to
#   insertion sort (cheaper constants). If recursion exceeds 2*log2(n),
#   switch to heap sort (kills the O(n^2) case). This is C++ std::sort.
#
# INVARIANT
#   Quick sort's partition invariant holds, plus: recursion depth never
#   exceeds maxdepth before heap sort takes over.
#
# COMPLEXITY  best O(n log n) | avg O(n log n) | worst O(n log n)
# SPACE       O(log n)
# PROPERTIES  stable no  in-place yes  adaptive no
#
# REACH FOR IT WHEN
#   You want quick sort's speed with a guaranteed worst case. The right
#   default for arrays.
#
# AVOID WHEN
#   Stability required — use tim sort.
#
# PITFALLS
#   1. The depth limit must be decremented per recursive call, not per
#      partition, or the heap-sort fallback never fires.
#   2. Falling back to heap sort on the *whole* array rather than the
#      current sub-range corrupts already-partitioned regions.
#   3. The insertion-sort threshold is a tuned constant (typically 16).
#      Setting it to 1 makes the hybrid pointless.
#
# SEE ALSO    quick_sort, heap_sort, insertion_sort, tim_sort
#
# INTERVIEW
#   - Why does std::sort guarantee O(n log n) when quick sort does not?
# --- end curriculum ---

import math


def insertion_sort(arr, left, right):
    for i in range(left + 1, right + 1):
        temp = arr[i]
        j = i - 1
        while j >= left and arr[j] > temp:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = temp

def heapify(arr, n, i, left):
    largest = i
    low = 2 * (i - left) + 1 + left
    r = 2 * (i - left) + 2 + left
    if low < n and arr[low] > arr[largest]:
        largest = low
    if r < n and arr[r] > arr[largest]:
        largest = r
    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]
        heapify(arr, n, largest, left)

def heap_sort(arr, left, right):
    n = right + 1
    for i in range((left + n) // 2 - 1, left - 1, -1):
        heapify(arr, n, i, left)
    for i in range(right, left, -1):
        arr[left], arr[i] = arr[i], arr[left]
        heapify(arr, i, left, left)

def partition(arr, low, high):
    pivot = arr[high]
    i = low - 1
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]
    arr[i+1], arr[high] = arr[high], arr[i+1]
    return i + 1

def introsort_util(arr, left, right, maxdepth):
    size_threshold = 16  # For small arrays, use insertion sort
    if right - left <= size_threshold:
        insertion_sort(arr, left, right)
    elif maxdepth == 0:
        heap_sort(arr, left, right)
    else:
        pivot = partition(arr, left, right)
        introsort_util(arr, left, pivot - 1, maxdepth - 1)
        introsort_util(arr, pivot + 1, right, maxdepth - 1)

def introsort(arr):
    """
    Sorts 'arr' in-place using IntroSort (Quick Sort + Heap Sort + Insertion Sort).
    """
    n = len(arr)
    maxdepth = int(2 * math.log2(n)) if n > 0 else 0
    introsort_util(arr, 0, n - 1, maxdepth)
    return arr  # Optional, for chaining
