# --- curriculum: shell_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# SHELL SORT  (Sorting / advanced)
#
# MENTAL MODEL
#   Insertion sort's weakness is that an element can only move one slot per
#   swap. So run insertion sort on elements a gap apart, shrinking the gap
#   to 1. Early large-gap passes move values a long way cheaply; the final
#   gap-1 pass is a plain insertion sort on nearly-sorted data.
#
# INVARIANT
#   After the pass with gap g, the array is g-sorted: arr[i] <= arr[i+g] for
#   every valid i.
#
# COMPLEXITY  best O(n log n) | avg depends on gap sequence | worst O(n^2) (halving gaps)
# SPACE       O(1)
# PROPERTIES  stable no  in-place yes  adaptive yes
#
# REACH FOR IT WHEN
#   Medium n, no recursion allowed, O(1) space required — common in embedded
#   code.
#
# AVOID WHEN
#   You need a provable bound: its complexity is an open problem for good
#   gap sequences.
#
# PITFALLS
#   1. The gap sequence IS the algorithm. Naive halving gives O(n^2); Ciura
#      or Sedgewick sequences are what make it competitive.
#   2. Long-range swaps hop over equal values, so it is not stable —
#      surprising to people who think of it as 'just insertion sort'.
#   3. The loop must still end with gap == 1, or the array is only g-sorted
#      and not sorted.
#
# SEE ALSO    insertion_sort, comb_sort, tim_sort
#
# INTERVIEW
#   - Rarely asked; cited as the 'gap' idea behind comb sort
# --- end curriculum ---

def shell_sort(arr):
    """
    Sorts the input list 'arr' in-place using Shell Sort.

    Time Complexity: Best: O(N log N), Worst: depends on gap sequence (typically O(N^2))
    Space Complexity: O(1) (in-place)
    """
    n = len(arr)
    gap = n // 2  # Initial gap size

    # Reduce gap and perform gapped insertion sort
    while gap > 0:
        for i in range(gap, n):
            temp = arr[i]
            j = i
            # Shift earlier gap-sorted elements up until correct location for arr[i] is found
            while j >= gap and arr[j - gap] > temp:
                arr[j] = arr[j - gap]
                j -= gap
            arr[j] = temp
        gap //= 2  # Reduce the gap for next pass
    return arr  # Optional, for chaining
