# --- curriculum: tim_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# TIM SORT  (Sorting / advanced)
#
# MENTAL MODEL
#   Real data arrives in runs. Insertion-sort fixed-size blocks, then
#   merge-sort the blocks together, doubling the merge width each round.
#   This is CPython's list.sort and Java's Arrays.sort for objects.
#
# INVARIANT
#   After the run-building phase every block of RUN elements is sorted;
#   after the merge pass of width w every block of 2w is sorted.
#
# COMPLEXITY  best O(n) | avg O(n log n) | worst O(n log n)
# SPACE       O(n)
# PROPERTIES  stable yes  in-place no  adaptive yes
#
# REACH FOR IT WHEN
#   The general-purpose default for real-world, partially-ordered data.
#
# AVOID WHEN
#   Space is tight, or data is uniformly random (plain merge sort is simpler
#   for the same cost).
#
# PITFALLS
#   1. Production timsort detects *natural* runs of varying length and
#      reverses descending ones; the fixed-RUN version here is the
#      simplified teaching form and is not adaptive in the same way.
#   2. Merging must walk widths 2*RUN, 4*RUN, ... and clamp the right edge
#      to n-1, or the last partial block is dropped.
#   3. Stability depends on the merge taking from the left run on ties, same
#      as plain merge sort.
#
# SEE ALSO    merge_sort, insertion_sort, intro_sort
#
# INTERVIEW
#   - Why is Python's sort stable and fast on real data?
#   - Merge Intervals (LC 56) — sorting nearly-ordered input
# --- end curriculum ---

def insertion_sort_run(arr, left, right):
    """
    Helper function to sort a subarray arr[left:right+1] using insertion sort.
    """
    for i in range(left + 1, right + 1):
        temp = arr[i]
        j = i - 1
        while j >= left and arr[j] > temp:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = temp

def merge(arr, low, m, r):
    """
    Helper function to merge two sorted subarrays arr[low:m+1] and arr[m+1:r+1].
    """
    len1, len2 = m - low + 1, r - m
    left = arr[low:m + 1]
    right = arr[m + 1:r + 1]
    i = j = 0
    k = low
    while i < len1 and j < len2:
        if left[i] <= right[j]:
            arr[k] = left[i]
            i += 1
        else:
            arr[k] = right[j]
            j += 1
        k += 1
    while i < len1:
        arr[k] = left[i]
        i += 1
        k += 1
    while j < len2:
        arr[k] = right[j]
        j += 1
        k += 1

def tim_sort(arr):
    """
    Simplified Timsort implementation.
    """
    n = len(arr)
    RUN = 32

    # Step 1: Sort small runs using insertion sort
    for start in range(0, n, RUN):
        end = min(start + RUN - 1, n - 1)
        insertion_sort_run(arr, start, end)

    # Step 2: Merge runs
    size = RUN
    while size < n:
        for left in range(0, n, 2 * size):
            mid = min(n - 1, left + size - 1)
            right = min((left + 2 * size - 1), n - 1)
            if mid < right:
                merge(arr, left, mid, right)
        size *= 2
    return arr  # Optional, for chaining
