# --- curriculum: traversals ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# TREE TRAVERSALS  (Structures / trees)
#
# MENTAL MODEL
#   Four orders, each suited to a different job. Preorder (root first)
#   copies or serialises. Inorder (root in the middle) sorts a BST.
#   Postorder (root last) frees or evaluates bottom-up. Level-order
#   (breadth-first) measures distance from the root.
#
# INVARIANT
#   Every node is visited exactly once; the order is fixed by where the root
#   is processed relative to its subtrees.
#
# COMPLEXITY  best O(n) | avg O(n) | worst O(n)
# SPACE       O(h) DFS / O(w) BFS
#
# REACH FOR IT WHEN
#   Choose by what you need: inorder for sorted output, postorder for
#   bottom-up aggregation, level-order for depth.
#
# AVOID WHEN
#   Never — but picking the wrong order turns an easy problem into a hard
#   one.
#
# PITFALLS
#   1. Postorder is required whenever a node's answer depends on its
#      children's answers (height, diameter, subtree sums). Using preorder
#      there forces redundant recomputation.
#   2. DFS uses O(h) space, BFS uses O(w) where w is the widest level. For a
#      balanced tree that is O(log n) versus O(n) — BFS is the expensive
#      one, which surprises people.
#   3. Iterative inorder needs an explicit stack and a 'go left as far as
#      possible' loop. Morris traversal does it in O(1) space by temporarily
#      rewiring the tree.
#
# SEE ALSO    binary_tree, bst, stack, queue, undirected_graph
#
# INTERVIEW
#   - Binary Tree Inorder Traversal (LC 94) — iterative
#   - Binary Tree Level Order Traversal (LC 102)
#   - Serialize and Deserialize Binary Tree (LC 297)
#   - Construct Tree from Preorder and Inorder (LC 105)
# --- end curriculum ---

from Non_Linear.trees.binary_tree import Node


class TreeTraversals:
    @staticmethod
    def iterative_inorder(root: 'Node') -> list[int]:
      """
      Performs an iterative inorder traversal (Left -> Root -> Right).

      Args:
          root (Node): The root of the binary tree.

      Returns:
          list[int]: A list of node values in inorder sequence.

      Time Complexity: O(n)
      Space Complexity: O(h) — h = height of the tree (stack depth)
      """
      stack, result = [], []
      current = root

      while current or stack:
          # Reach the leftmost Node of the current Node
          while current:
              stack.append(current)
              current = current.left

          # Current is None here, so we backtrack
          current = stack.pop()
          result.append(current.value)

          # Visit the right subtree
          current = current.right

      return result

    @staticmethod
    def iterative_preorder(root: 'Node') -> list[int]:
        """
        Performs an iterative preorder traversal (Root -> Left -> Right).

        Args:
            root (Node): The root of the binary tree.

        Returns:
            list[int]: A list of node values in preorder sequence.

        Time Complexity: O(n)
        Space Complexity: O(h)
        """
        if not root:
            return []

        stack, result = [root], []

        while stack:
            current = stack.pop()
            result.append(current.value)

            # Push right first so that left is processed first
            if current.right:
                stack.append(current.right)
            if current.left:
                stack.append(current.left)

        return result

    @staticmethod
    def iterative_postorder(root: 'Node') -> list[int]:
        """
        Performs an iterative postorder traversal (Left -> Right -> Root)
        using a modified reverse preorder trick.

        Args:
            root (Node): The root of the binary tree.

        Returns:
            list[int]: A list of node values in postorder sequence.

        Time Complexity: O(n)
        Space Complexity: O(h)
        """
        if not root:
            return []

        stack, result = [root], []

        while stack:
            current = stack.pop()
            result.append(current.value)

            # Push left first so right is processed before left
            if current.left:
                stack.append(current.left)
            if current.right:
                stack.append(current.right)

        # Reverse the process to get left → right → root
        return result[::-1]
