# --- curriculum: max_heap ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# MAX HEAP  (Structures / heaps)
#
# MENTAL MODEL
#   The mirror image of a min heap: every parent is >= its children, so the
#   maximum sits at index 0. The engine inside heap sort, and the half of a
#   two-heap median tracker that holds the lower values.
#
# INVARIANT
#   For every index i > 0: data[(i-1)//2] >= data[i].
#
# COMPLEXITY  best O(1) peek max | avg O(log n) insert/extract | worst O(log n)
# SPACE       O(n)
#
# REACH FOR IT WHEN
#   Largest-first priority, heap sort, bounded 'k smallest' (max-heap of
#   size k), median maintenance.
#
# AVOID WHEN
#   Same as min heap — no ordered iteration, no cheap arbitrary search.
#
# PITFALLS
#   1. Python's heapq is min-only. The standard trick is to push negated
#      values, which breaks on non-numeric keys and is easy to forget to
#      undo on pop.
#   2. replace() (pop-then-push in one sift) is cheaper than separate
#      extract and insert — one O(log n) pass instead of two.
#   3. Same 0-based versus 1-based child index trap as the min heap.
#
# SEE ALSO    min_heap, heap_sort, selection_sort
#
# INTERVIEW
#   - Last Stone Weight (LC 1046)
#   - Find Median from Data Stream (LC 295)
#   - K Closest Points to Origin (LC 973) — max-heap of size k
#
# LONGER NOTE docs/heaps.md
# --- end curriculum ---

from typing import Generic, TypeVar

# Any value supporting "<" works here, not just int.
T = TypeVar("T")

class MaxHeap(Generic[T]):
    """
    A Max-Heap implementation using an array (list) for storage.
    Provides O(log n) insertion and extraction of the maximum element.
    """

    def __init__(self):
        """
        Initialize an empty max-heap.
        Time Complexity: O(1)
        Space Complexity: O(1)
        """
        self.data: list[T] = []

    def __len__(self) -> int:
        """
        Return the number of elements in the heap.
        Time Complexity: O(1)
        Space Complexity: O(1)
        """
        return len(self.data)


    def insert(self, value: T) -> None:
      """
      Insert a value into the heap, maintaining the max-heap property.
      Time Complexity: O(log n)
      Space Complexity: O(1)
      """
      self.data.append(value)
      self._bubble_up(len(self.data) - 1)


    def _bubble_up(self, index: int) -> None:
      """
      Move the element at the given index up to restore the max-heap property.
      Time Complexity: O(log n)
      Space Complexity: O(1)
      """
      parent = (index - 1) // 2
      while index > 0 and self.data[index] > self.data[parent]:
          self.data[index], self.data[parent] = self.data[parent], self.data[index]
          index = parent
          parent = (index - 1) // 2


    def extract_max(self) -> T | None:
      """
      Remove and return the maximum element from the heap.
      Time Complexity: O(log n)
      Space Complexity: O(1)
      """
      if not self.data:
          return None
      max_val = self.data[0]
      last_val = self.data.pop()
      if self.data:
          self.data[0] = last_val
          self._bubble_down(0)
      return max_val


    def _bubble_down(self, index: int) -> None:
      """
      Move the element at index down to restore the max-heap property.
      Time Complexity: O(log n)
      Space Complexity: O(1)
      """
      n = len(self.data)
      while True:
          left = 2 * index + 1
          right = 2 * index + 2
          largest = index

          if left < n and self.data[left] > self.data[largest]:
              largest = left
          if right < n and self.data[right] > self.data[largest]:
              largest = right

          if largest == index:
              break
          self.data[index], self.data[largest] = self.data[largest], self.data[index]
          index = largest


    # In most heap implementations, peek() and get_max() (or top()) are actually the same method under different names.
    def get_max(self) -> T | None:
      """
      Return the maximum element from the heap without removing it.
      Time Complexity: O(1)
      Space Complexity: O(1)
      """
      if not self.data:
          return None
      return self.data[0]


    def replace(self, value: T) -> T | None:
      """
      Remove and return the maximum element, replacing it with a new value.
      Restores max-heap property by bubbling down from root.
      Time Complexity: O(log n)
      Space Complexity: O(1)
      """
      if not self.data:
          self.data.append(value)
          return None  # No previous max to return
      max_val = self.data[0]
      self.data[0] = value
      self._bubble_down(0)
      return max_val


    def heapify(self, elements: list[T]) -> None:
      """
      Transform a list of elements into a valid max-heap in O(n) time.
      Time Complexity: O(n)
      Space Complexity: O(n) (for the data list)
      """
      self.data = elements[:]
      n = len(self.data)
      # Start from the last parent and heapify-down each node
      for i in reversed(range(n // 2)):
          self._bubble_down(i)
