# --- curriculum: min_heap ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# MIN HEAP  (Structures / heaps)
#
# MENTAL MODEL
#   A complete binary tree flattened into an array, where every parent is <=
#   its children. That weaker-than-BST ordering is exactly enough to keep
#   the minimum at index 0, and weak enough to maintain in O(log n) with no
#   pointers at all.
#
# INVARIANT
#   For every index i > 0: data[(i-1)//2] <= data[i]. Children of i are 2i+1
#   and 2i+2.
#
# COMPLEXITY  best O(1) peek min | avg O(log n) insert/extract | worst O(log n)
# SPACE       O(n)
#
# REACH FOR IT WHEN
#   Priority queues, kth-smallest, merging k sorted streams, Dijkstra, A*,
#   scheduling, streaming medians.
#
# AVOID WHEN
#   You need sorted iteration or arbitrary search — a heap gives you the
#   extremum and nothing else cheaply.
#
# PITFALLS
#   1. A heap is NOT sorted. Only index 0 is guaranteed. Printing the
#      backing array and expecting order is the classic misconception.
#   2. Heapifying an existing array bottom-up is O(n); inserting n items one
#      at a time is O(n log n). Do not confuse the two.
#   3. Child indices are 2i+1 / 2i+2 for 0-based arrays and 2i / 2i+1 for
#      1-based. Mixing them corrupts the heap without raising.
#   4. For kth LARGEST keep a min-heap of size k (not a max-heap of
#      everything) — that is O(n log k) space-bounded.
#
# SEE ALSO    max_heap, heap_sort, cartesian_tree_sort, astar, external_merge_sort
#
# INTERVIEW
#   - Kth Largest Element in an Array (LC 215)
#   - Merge k Sorted Lists (LC 23)
#   - Find Median from Data Stream (LC 295) — two heaps
#   - Task Scheduler (LC 621)
#   - K Closest Points to Origin (LC 973)
#
# LONGER NOTE docs/heaps.md
# --- end curriculum ---

from typing import Generic, TypeVar

# Any value supporting "<" works here, not just int.
T = TypeVar("T")

class MinHeap(Generic[T]):
    """
    A Min-Heap implementation using an array (list) for storage.
    Provides O(log n) insertion and extraction of the minimum element.
    """

    def __init__(self):
        """Initialize an empty min-heap."""
        self.data: list[T] = []


    def insert(self, value: T) -> None:
        """
        Insert a value into the heap, maintaining the min-heap property.
        Time Complexity: O(log n)
        Space Complexity: O(1)
        """
        self.data.append(value) # appends the new value at the end of the list to maintain the heap as complete binary tree
        self._bubble_up(len(self.data) - 1) # Bubble up from new values position
        #  The new value might be smaller than its parent, which would break the min-heap property, so we move it up until order is restored.


    def extract_min(self) -> T | None:
        """
        Remove and return the minimum element from the heap.
        Time Complexity: O(log n)
        Space Complexity: O(1)
        """
        # Handle empty heap
        if not self.data:
            return None
        min_val = self.data[0] # Stores the first element from the list which is minimum
        last_val = self.data.pop() # Removes the last element and stores it
        if self.data:
            self.data[0] = last_val
            self._bubble_down(0) # The last element (now at the root) might be greater than its children, breaking the min-heap rule.
            # Fix this by "bubbling down" from the root using _bubble_down(0).
        return min_val # after restoring the heap order return the value you removed


    def get_min(self) -> T | None:
        """
        Get the minimum element without removing it.
        Time Complexity: O(1)
        Space Complexity: O(1)
        """
        if not self.data:
            return None
        return self.data[0]


    def _bubble_up(self, index: int) -> None:
        """
        Restore the heap property going up from index.

        After append, only one thing can break: the new element might be smaller than its parent. This method moves the element up until the parent is smaller or it reaches the root.

        """
        parent = (index - 1) // 2 # calculates parent index for the current node
        # As long as we’re not at the root (index > 0) and the current value is less than its parent, keep moving up.
        while index > 0 and self.data[index] < self.data[parent]:
            self.data[index], self.data[parent] = self.data[parent], self.data[index] # Swap the current node and its parent.
            # Move up one level and repeat the check.
            index = parent
            parent = (index - 1) // 2


    def _bubble_down(self, index: int) -> None:
        """
        Restore the heap property going down from index.

        After removing the min element (the root), we move the last element to the root

        This new root might break the min-heap property: it could be larger than its children.

        Goal: Move it down to its correct spot so every parent is less than or equal to its children.

        """
        n = len(self.data)
        while True:
            left = 2 * index + 1
            right = 2 * index + 2
            smallest = index

            if left < n and self.data[left] < self.data[smallest]:
                smallest = left
            if right < n and self.data[right] < self.data[smallest]:
                smallest = right

            if smallest == index:
                break
            self.data[index], self.data[smallest] = self.data[smallest], self.data[index]
            index = smallest


    def __len__(self) -> int:
        """Return the number of elements in the heap."""
        return len(self.data)


    def __str__(self) -> str:
        """String representation for debugging."""
        return str(self.data)
