# --- curriculum: bucket_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# BUCKET SORT  (Sorting / non-comparison)
#
# MENTAL MODEL
#   Scatter values into k buckets by value range, sort each bucket with
#   something simple, then read the buckets in order. Fast only if the input
#   is spread evenly, so that each bucket stays tiny.
#
# INVARIANT
#   Every value in bucket i is < every value in bucket i+1, so concatenating
#   sorted buckets in index order yields a sorted array.
#
# COMPLEXITY  best O(n + k) | avg O(n + k) | worst O(n^2)
# SPACE       O(n + k)
# PROPERTIES  stable yes  in-place no  adaptive no
#
# REACH FOR IT WHEN
#   Values are roughly uniformly distributed over a known range — sampled
#   sensor data, random floats.
#
# AVOID WHEN
#   The distribution is skewed or unknown: everything lands in one bucket
#   and you get insertion sort's worst case.
#
# PITFALLS
#   1. Its cost depends on value *distribution*, unlike counting and radix
#      sort which depend on value *range*. That distinction is the usual
#      interview follow-up.
#   2. The classic textbook version assumes values in [0, 1) and crashes on
#      anything else; this implementation rescales by min/max instead.
#   3. The maximum value maps to exactly index k and must be clamped to k-1,
#      or it writes past the last bucket.
#
# SEE ALSO    counting_sort, radix_sort, insertion_sort, quick_sort
#
# INTERVIEW
#   - Top K Frequent Elements (LC 347) — bucket by frequency
#   - Maximum Gap (LC 164)
# --- end curriculum ---

"""Bucket sort — scatter into ranges, sort each range, concatenate."""

from collections.abc import Callable

from Sorting.simple.insertion_sort import insertion_sort


def bucket_sort(
    arr: list[float],
    bucket_count: int | None = None,
    inner_sort: Callable[[list[float]], list[float]] = insertion_sort,
) -> list[float]:
    """
    Sort `arr` in place by scattering values into value-range buckets.

    Values are mapped to buckets by linear interpolation between min and max, so
    any numeric range works — not just [0, 1). Each bucket is then sorted with
    `inner_sort` (insertion sort by default, because buckets are expected to be
    tiny and insertion sort is the fastest thing there) and the buckets are
    concatenated in order.

    Time:  O(n + k) when values are spread evenly over k buckets;
           O(n^2) when every value lands in one bucket (skewed input)
    Space: O(n + k)

    The performance claim rests entirely on the *distribution* of the input,
    which is what separates bucket sort from counting and radix sort: those
    depend on the value range, this one depends on value uniformity.
    """
    n = len(arr)
    if n <= 1:
        return arr

    min_val = min(arr)
    max_val = max(arr)
    if min_val == max_val:
        return arr

    k = bucket_count if bucket_count is not None else n
    buckets: list[list[float]] = [[] for _ in range(k)]

    value_span = max_val - min_val
    for num in arr:
        # Scale into [0, k); max_val would land at exactly k, so clamp it down.
        index = int((num - min_val) / value_span * k)
        if index == k:
            index = k - 1
        buckets[index].append(num)

    write_index = 0
    for bucket in buckets:
        inner_sort(bucket)
        for num in bucket:
            arr[write_index] = num
            write_index += 1

    return arr
