# --- curriculum: counting_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# COUNTING SORT  (Sorting / non-comparison)
#
# MENTAL MODEL
#   Do not compare — count. Tally how many of each value there is, turn the
#   tallies into running totals (so each value knows its output index), then
#   place values from the back to keep equal ones in order. Beats the n log
#   n comparison bound by not comparing.
#
# INVARIANT
#   After the prefix-sum step, count[v - min] is one past the last output
#   index reserved for value v.
#
# COMPLEXITY  best O(n + k) | avg O(n + k) | worst O(n + k)
# SPACE       O(n + k)
# PROPERTIES  stable yes  in-place no  adaptive no
#
# REACH FOR IT WHEN
#   Integer keys with a small range k — ages, scores, bytes, bucket indices.
#
# AVOID WHEN
#   k >> n (the count array dwarfs the data), or keys are floats/strings.
#
# PITFALLS
#   1. Iterating the input FORWARD when placing breaks stability, which then
#      breaks radix sort if you use this as its inner pass.
#   2. Offsetting by min_val is what allows negative keys; forgetting it
#      gives an IndexError on any negative input.
#   3. k is the value *range*, not the value count: sorting [1, 1000000]
#      allocates a million slots for two elements.
#
# SEE ALSO    radix_sort, pigeonhole_sort, bucket_sort
#
# INTERVIEW
#   - Sort Characters By Frequency (LC 451)
#   - H-Index (LC 274)
#   - Maximum Gap (LC 164)
#   - Relative Sort Array (LC 1122)
# --- end curriculum ---

def counting_sort(arr):
    """
    Sorts a list of non-negative integers using Counting Sort.
    Returns a new sorted list.

    Time Complexity: O(N + K), where N = len(arr), K = range of input
    Space Complexity: O(N + K)
    """
    if not arr:
        return arr

    max_val = max(arr)
    min_val = min(arr)
    range_of_elements = max_val - min_val + 1

    # Initialize count array
    count = [0] * range_of_elements

    # Store the count of each element
    for num in arr:
        count[num - min_val] += 1

    # Change count[i] so that it contains actual position of this number in output array
    for i in range(1, len(count)):
        count[i] += count[i - 1]

    # Build the output array
    output = [0] * len(arr)
    # To make it stable, iterate in reverse order
    for num in reversed(arr):
        count[num - min_val] -= 1
        output[count[num - min_val]] = num

    return output
