# --- curriculum: pigeonhole_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# PIGEONHOLE SORT  (Sorting / non-comparison)
#
# MENTAL MODEL
#   One hole per distinct value in the range. Drop each element in its hole,
#   then walk the holes in order emptying them. Counting sort without the
#   prefix-sum step — it reconstructs values instead of moving them.
#
# INVARIANT
#   holes[v - min] holds exactly the count of value v present in the input.
#
# COMPLEXITY  best O(n + range) | avg O(n + range) | worst O(n + range)
# SPACE       O(range)
# PROPERTIES  stable yes  in-place no  adaptive no
#
# REACH FOR IT WHEN
#   Integer keys where the range is close to n — essentially a permutation.
#
# AVOID WHEN
#   Range greatly exceeds n, or keys carry attached data (see below).
#
# PITFALLS
#   1. Because it rebuilds values from counts rather than moving records, it
#      cannot carry satellite data. Counting sort can. That is the real
#      difference between the two, not the complexity.
#   2. 'Stable' is vacuous here: identical keys are indistinguishable once
#      reduced to a count.
#   3. Allocates max - min + 1 slots, so one outlier value blows up memory.
#
# SEE ALSO    counting_sort, bucket_sort
#
# INTERVIEW
#   - Missing Number (LC 268)
#   - First Missing Positive (LC 41) — index-as-hole trick
# --- end curriculum ---

def pigeonhole_sort(arr):
    """
    Sorts a list of integers using Pigeonhole Sort.
    Returns a new sorted list.

    Time Complexity: O(N + Range), where Range = max(arr) - min(arr) + 1
    Space Complexity: O(N + Range)
    """
    if not arr:
        return arr

    min_val = min(arr)
    max_val = max(arr)
    size = max_val - min_val + 1

    # Step 1: Create holes (buckets) and initialize counts
    holes = [0] * size

    # Step 2: Populate holes
    for num in arr:
        holes[num - min_val] += 1

    # Step 3: Put elements back into arr
    idx = 0
    for i in range(size):
        while holes[i] > 0:
            arr[idx] = i + min_val
            idx += 1
            holes[i] -= 1
    return arr  # Optional, for chaining
