# --- curriculum: radix_sort ---
# generated by `python -m Utils.sync` from curriculum/ -- edit there, not here
#
# RADIX SORT  (Sorting / non-comparison)
#
# MENTAL MODEL
#   Sort by the least significant digit, then the next, and so on. Each pass
#   is a stable counting sort on one digit. Because every pass is stable,
#   the ordering established by earlier (less significant) digits survives —
#   that is the whole trick.
#
# INVARIANT
#   After the pass on digit position d, the array is correctly sorted by the
#   last d+1 digits of every key.
#
# COMPLEXITY  best O(d(n + b)) | avg O(d(n + b)) | worst O(d(n + b))
# SPACE       O(n + b)
# PROPERTIES  stable yes  in-place no  adaptive no
#
# REACH FOR IT WHEN
#   Fixed-width integer or string keys, large n — often beats quick sort on
#   32-bit ints.
#
# AVOID WHEN
#   Variable-length or float keys without transformation; very small n
#   (setup cost dominates).
#
# PITFALLS
#   1. The per-digit sort MUST be stable. Swap in a non-stable inner sort
#      and the result is wrong in a way that passes small tests.
#   2. LSD-first is for fixed-width keys. MSD-first is needed for
#      variable-length strings and is a different algorithm.
#   3. Negative numbers need separate handling: split by sign, sort the
#      magnitudes, reverse the negatives. The implementation here takes
#      non-negative integers only.
#
# SEE ALSO    counting_sort, bucket_sort, trie
#
# INTERVIEW
#   - Maximum Gap (LC 164)
#   - Sort integers without comparisons
# --- end curriculum ---

def counting_sort_exp(arr, exp):
    """
    A stable counting sort for the digit at exp (1, 10, 100, ...)
    """
    n = len(arr)
    output = [0] * n
    count = [0] * 10  # For decimal digits (0-9)

    # Store count of occurrences in count[]
    for num in arr:
        index = (num // exp) % 10
        count[index] += 1

    # Change count[i] so that count[i] now contains actual position
    for i in range(1, 10):
        count[i] += count[i - 1]

    # Build output array (stable, so iterate in reverse)
    for num in reversed(arr):
        index = (num // exp) % 10
        count[index] -= 1
        output[count[index]] = num

    # Copy output array to arr
    for i in range(n):
        arr[i] = output[i]

def radix_sort(arr):
    """
    Sorts a list of non-negative integers using Radix Sort (LSD variant).

    Time Complexity: O(N * d), where d = max number of digits
    Space Complexity: O(N)
    """
    if not arr:
        return arr

    max_num = max(arr)
    exp = 1
    while max_num // exp > 0:
        counting_sort_exp(arr, exp)
        exp *= 10
    return arr  # Optional, for chaining
